package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class UserDiscuss {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_discuss.id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_discuss.course_hour_id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	private Long course_hour_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_discuss.user_id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_discuss.discuss_time
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	private Date discuss_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_discuss.discuss_content
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	private String discuss_content;

	private Long class_id;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_discuss.id
	 * @return  the value of user_discuss.id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_discuss.id
	 * @param id  the value for user_discuss.id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_discuss.course_hour_id
	 * @return  the value of user_discuss.course_hour_id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public Long getCourse_hour_id() {
		return course_hour_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_discuss.course_hour_id
	 * @param course_hour_id  the value for user_discuss.course_hour_id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public void setCourse_hour_id(Long course_hour_id) {
		this.course_hour_id = course_hour_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_discuss.user_id
	 * @return  the value of user_discuss.user_id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_discuss.user_id
	 * @param user_id  the value for user_discuss.user_id
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_discuss.discuss_time
	 * @return  the value of user_discuss.discuss_time
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public Date getDiscuss_time() {
		return discuss_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_discuss.discuss_time
	 * @param discuss_time  the value for user_discuss.discuss_time
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public void setDiscuss_time(Date discuss_time) {
		this.discuss_time = discuss_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_discuss.discuss_content
	 * @return  the value of user_discuss.discuss_content
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public String getDiscuss_content() {
		return discuss_content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_discuss.discuss_content
	 * @param discuss_content  the value for user_discuss.discuss_content
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	public void setDiscuss_content(String discuss_content) {
		this.discuss_content = discuss_content;
	}

	public Long getClass_id() {
		return class_id;
	}

	public void setClass_id(Long class_id) {
		this.class_id = class_id;
	}
}