package cn.bnsr.edu_yun.frontstage.train.po;

public class CourseNoteAgree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_note_agree.id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_note_agree.user_id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_note_agree.note_id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    private Long note_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_note_agree.id
     *
     * @return the value of course_note_agree.id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_note_agree.id
     *
     * @param id the value for course_note_agree.id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_note_agree.user_id
     *
     * @return the value of course_note_agree.user_id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_note_agree.user_id
     *
     * @param user_id the value for course_note_agree.user_id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_note_agree.note_id
     *
     * @return the value of course_note_agree.note_id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    public Long getNote_id() {
        return note_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_note_agree.note_id
     *
     * @param note_id the value for course_note_agree.note_id
     *
     * @mbggenerated Wed Nov 02 13:56:28 CST 2016
     */
    public void setNote_id(Long note_id) {
        this.note_id = note_id;
    }
}