package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.title
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.subtitle
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private String subtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.status
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.serial_status
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Integer serial_status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.create_time
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Date create_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.user_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.type
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.classify_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Long classify_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.validity
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Integer validity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.teacher_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Long teacher_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.student_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Long student_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.course_info_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private Long course_info_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.hours
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	private String hours;
	
	private String room_id;
	
	private int is_check;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.id
	 * @return  the value of course.id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.id
	 * @param id  the value for course.id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.title
	 * @return  the value of course.title
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.title
	 * @param title  the value for course.title
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.subtitle
	 * @return  the value of course.subtitle
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public String getSubtitle() {
		return subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.subtitle
	 * @param subtitle  the value for course.subtitle
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.status
	 * @return  the value of course.status
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.status
	 * @param status  the value for course.status
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.serial_status
	 * @return  the value of course.serial_status
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Integer getSerial_status() {
		return serial_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.serial_status
	 * @param serial_status  the value for course.serial_status
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setSerial_status(Integer serial_status) {
		this.serial_status = serial_status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.create_time
	 * @return  the value of course.create_time
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.create_time
	 * @param create_time  the value for course.create_time
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.user_id
	 * @return  the value of course.user_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.user_id
	 * @param user_id  the value for course.user_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.type
	 * @return  the value of course.type
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.type
	 * @param type  the value for course.type
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.classify_id
	 * @return  the value of course.classify_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Long getClassify_id() {
		return classify_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.classify_id
	 * @param classify_id  the value for course.classify_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setClassify_id(Long classify_id) {
		this.classify_id = classify_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.validity
	 * @return  the value of course.validity
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Integer getValidity() {
		return validity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.validity
	 * @param validity  the value for course.validity
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setValidity(Integer validity) {
		this.validity = validity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.teacher_id
	 * @return  the value of course.teacher_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Long getTeacher_id() {
		return teacher_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.teacher_id
	 * @param teacher_id  the value for course.teacher_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setTeacher_id(Long teacher_id) {
		this.teacher_id = teacher_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.student_id
	 * @return  the value of course.student_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Long getStudent_id() {
		return student_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.student_id
	 * @param student_id  the value for course.student_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setStudent_id(Long student_id) {
		this.student_id = student_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.course_info_id
	 * @return  the value of course.course_info_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public Long getCourse_info_id() {
		return course_info_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.course_info_id
	 * @param course_info_id  the value for course.course_info_id
	 * @mbggenerated  Thu Oct 27 14:36:25 CST 2016
	 */
	public void setCourse_info_id(Long course_info_id) {
		this.course_info_id = course_info_id;
	}

	public String getHours() {
		return hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	public String getRoom_id() {
		return room_id;
	}

	public void setRoom_id(String room_id) {
		this.room_id = room_id;
	}

	public int getIs_check() {
		return is_check;
	}

	public void setIs_check(int is_check) {
		this.is_check = is_check;
	}
	
	
}