package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class Plan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.name
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.community_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long community_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.credit
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.hour
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Integer hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.start_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Date start_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.user_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.create_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.status
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.end_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Date end_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.id
     *
     * @return the value of plan.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.id
     *
     * @param id the value for plan.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.name
     *
     * @return the value of plan.name
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.name
     *
     * @param name the value for plan.name
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.community_id
     *
     * @return the value of plan.community_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getCommunity_id() {
        return community_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.community_id
     *
     * @param community_id the value for plan.community_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setCommunity_id(Long community_id) {
        this.community_id = community_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.credit
     *
     * @return the value of plan.credit
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.credit
     *
     * @param credit the value for plan.credit
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.hour
     *
     * @return the value of plan.hour
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.hour
     *
     * @param hour the value for plan.hour
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.start_time
     *
     * @return the value of plan.start_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.start_time
     *
     * @param start_time the value for plan.start_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.user_id
     *
     * @return the value of plan.user_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.user_id
     *
     * @param user_id the value for plan.user_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.create_time
     *
     * @return the value of plan.create_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.create_time
     *
     * @param create_time the value for plan.create_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.status
     *
     * @return the value of plan.status
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.status
     *
     * @param status the value for plan.status
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.end_time
     *
     * @return the value of plan.end_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.end_time
     *
     * @param end_time the value for plan.end_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }
}