package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class StudentRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student_relation.id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student_relation.source_id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	private Long source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student_relation.source_type
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	private Integer source_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student_relation.user_id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student_relation.role_type
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	private Integer role_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student_relation.remarks
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	private String remarks;
	
	private Date create_time;
	
	private int level;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student_relation.id
	 * @return  the value of student_relation.id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student_relation.id
	 * @param id  the value for student_relation.id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student_relation.source_id
	 * @return  the value of student_relation.source_id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public Long getSource_id() {
		return source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student_relation.source_id
	 * @param source_id  the value for student_relation.source_id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public void setSource_id(Long source_id) {
		this.source_id = source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student_relation.source_type
	 * @return  the value of student_relation.source_type
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public Integer getSource_type() {
		return source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student_relation.source_type
	 * @param source_type  the value for student_relation.source_type
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public void setSource_type(Integer source_type) {
		this.source_type = source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student_relation.user_id
	 * @return  the value of student_relation.user_id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student_relation.user_id
	 * @param user_id  the value for student_relation.user_id
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student_relation.role_type
	 * @return  the value of student_relation.role_type
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public Integer getRole_type() {
		return role_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student_relation.role_type
	 * @param role_type  the value for student_relation.role_type
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public void setRole_type(Integer role_type) {
		this.role_type = role_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student_relation.remarks
	 * @return  the value of student_relation.remarks
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student_relation.remarks
	 * @param remarks  the value for student_relation.remarks
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}
}