package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class UserCert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.classes
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String classes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.complete_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date complete_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.study_name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String study_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.cert_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long cert_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.study_type
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer study_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.score
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.user_study_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long user_study_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cert.user_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.id
     *
     * @return the value of user_cert.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.id
     *
     * @param id the value for user_cert.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.classes
     *
     * @return the value of user_cert.classes
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.classes
     *
     * @param classes the value for user_cert.classes
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.complete_time
     *
     * @return the value of user_cert.complete_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getComplete_time() {
        return complete_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.complete_time
     *
     * @param complete_time the value for user_cert.complete_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setComplete_time(Date complete_time) {
        this.complete_time = complete_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.study_name
     *
     * @return the value of user_cert.study_name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getStudy_name() {
        return study_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.study_name
     *
     * @param study_name the value for user_cert.study_name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setStudy_name(String study_name) {
        this.study_name = study_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.cert_id
     *
     * @return the value of user_cert.cert_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getCert_id() {
        return cert_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.cert_id
     *
     * @param cert_id the value for user_cert.cert_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setCert_id(Long cert_id) {
        this.cert_id = cert_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.study_type
     *
     * @return the value of user_cert.study_type
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getStudy_type() {
        return study_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.study_type
     *
     * @param study_type the value for user_cert.study_type
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setStudy_type(Integer study_type) {
        this.study_type = study_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.score
     *
     * @return the value of user_cert.score
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.score
     *
     * @param score the value for user_cert.score
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.user_study_id
     *
     * @return the value of user_cert.user_study_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getUser_study_id() {
        return user_study_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.user_study_id
     *
     * @param user_study_id the value for user_cert.user_study_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setUser_study_id(Long user_study_id) {
        this.user_study_id = user_study_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cert.user_id
     *
     * @return the value of user_cert.user_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cert.user_id
     *
     * @param user_id the value for user_cert.user_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }
}