package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.train.po.TrainPhase;
import cn.bnsr.edu_yun.frontstage.train.view.TrainPhaseView;
import cn.bnsr.edu_yun.frontstage.train.view.TrainView;

public interface TrainPhaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_phase
	 * @mbggenerated  Wed Mar 22 14:34:43 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_phase
	 * @mbggenerated  Wed Mar 22 14:34:43 CST 2017
	 */
	int insert(TrainPhase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_phase
	 * @mbggenerated  Wed Mar 22 14:34:43 CST 2017
	 */
	int insertSelective(TrainPhase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_phase
	 * @mbggenerated  Wed Mar 22 14:34:43 CST 2017
	 */
	TrainPhase selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_phase
	 * @mbggenerated  Wed Mar 22 14:34:43 CST 2017
	 */
	int updateByPrimaryKeySelective(TrainPhase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_phase
	 * @mbggenerated  Wed Mar 22 14:34:43 CST 2017
	 */
	int updateByPrimaryKey(TrainPhase record);

	List<TrainPhaseView> queryTrainPhase(@Param("trainId")Long trainId,@Param("userId")Long userId);

	Integer searchTotalHours(@Param("trainId")Long trainId);
	
	int queryPhaseOfTrainPhaseCount(@Param("train_id")Long train_id);
	
	List<TrainPhaseView> queryTrainParseBaseMessage(TrainView trainView);
}