package cn.bnsr.edu_yun.frontstage.train.po;

public class Certificate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.id
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.up_score
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Integer up_score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.down_score
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Integer down_score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.cert_name
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private String cert_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.source_id
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Long source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.source_type
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Integer source_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.is_every
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Integer is_every;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certificate.is_every
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	private Long cert_model_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.id
	 * @return  the value of certificate.id
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.id
	 * @param id  the value for certificate.id
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.up_score
	 * @return  the value of certificate.up_score
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Integer getUp_score() {
		return up_score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.up_score
	 * @param up_score  the value for certificate.up_score
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setUp_score(Integer up_score) {
		this.up_score = up_score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.down_score
	 * @return  the value of certificate.down_score
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Integer getDown_score() {
		return down_score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.down_score
	 * @param down_score  the value for certificate.down_score
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setDown_score(Integer down_score) {
		this.down_score = down_score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.cert_name
	 * @return  the value of certificate.cert_name
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public String getCert_name() {
		return cert_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.cert_name
	 * @param cert_name  the value for certificate.cert_name
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setCert_name(String cert_name) {
		this.cert_name = cert_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.source_id
	 * @return  the value of certificate.source_id
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Long getSource_id() {
		return source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.source_id
	 * @param source_id  the value for certificate.source_id
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setSource_id(Long source_id) {
		this.source_id = source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.source_type
	 * @return  the value of certificate.source_type
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Integer getSource_type() {
		return source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.source_type
	 * @param source_type  the value for certificate.source_type
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setSource_type(Integer source_type) {
		this.source_type = source_type;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certificate.is_every
	 * @return  the value of certificate.is_every
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Integer getIs_every() {
		return is_every;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.is_every
	 * @param is_every  the value for certificate.is_every
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setIs_every(Integer is_every) {
		this.is_every = is_every;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.is_every
	 * @param is_every  the value for certificate.is_every
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public Long getCert_model_id() {
		return cert_model_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certificate.is_every
	 * @param is_every  the value for certificate.is_every
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	public void setCert_model_id(Long cert_model_id) {
		this.cert_model_id = cert_model_id;
	}
	
}