package cn.bnsr.edu_yun.backstage.base.po;

import java.math.BigDecimal;

public class Menu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.id
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.iconcls
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private String iconcls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.name
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.seq
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private BigDecimal seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.url
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.pid
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.isopen
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private Integer isopen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.shownotice
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	private Integer shownotice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.id
	 * @return  the value of menu.id
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.id
	 * @param id  the value for menu.id
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.iconcls
	 * @return  the value of menu.iconcls
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public String getIconcls() {
		return iconcls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.iconcls
	 * @param iconcls  the value for menu.iconcls
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setIconcls(String iconcls) {
		this.iconcls = iconcls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.name
	 * @return  the value of menu.name
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.name
	 * @param name  the value for menu.name
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.seq
	 * @return  the value of menu.seq
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public BigDecimal getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.seq
	 * @param seq  the value for menu.seq
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setSeq(BigDecimal seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.url
	 * @return  the value of menu.url
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.url
	 * @param url  the value for menu.url
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.pid
	 * @return  the value of menu.pid
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.pid
	 * @param pid  the value for menu.pid
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.isopen
	 * @return  the value of menu.isopen
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public Integer getIsopen() {
		return isopen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.isopen
	 * @param isopen  the value for menu.isopen
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setIsopen(Integer isopen) {
		this.isopen = isopen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.shownotice
	 * @return  the value of menu.shownotice
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public Integer getShownotice() {
		return shownotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.shownotice
	 * @param shownotice  the value for menu.shownotice
	 * @mbggenerated  Sun Aug 28 17:30:52 CST 2016
	 */
	public void setShownotice(Integer shownotice) {
		this.shownotice = shownotice;
	}
}