package cn.bnsr.edu_yun.frontstage.base.mapper;

import cn.bnsr.edu_yun.frontstage.base.po.IpIntercept;
import cn.bnsr.edu_yun.frontstage.base.view.IpIntercepterView;

public interface IpInterceptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ip_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ip_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	int insert(IpIntercept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ip_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	int insertSelective(IpIntercept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ip_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	IpIntercept selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ip_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	int updateByPrimaryKeySelective(IpIntercept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ip_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	int updateByPrimaryKey(IpIntercept record);
	
	IpIntercept queryIpInfoByIp(IpIntercepterView condition);
	
	void deleteAll();
	
}