package cn.bnsr.edu_yun.frontstage.resource.po;

import java.util.Date;

import cn.bnsr.edu_yun.frontstage.base.po.User;

public class File_comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.file_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long file_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.user_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.content
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.is_callback
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Byte is_callback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.callback_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long callback_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.agree
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Integer agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.disagree
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Integer disagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_comment.comment_time
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Date comment_time;
    private Byte score;
    private Byte status;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.id
     *
     * @return the value of file_comment.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.id
     *
     * @param id the value for file_comment.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.file_id
     *
     * @return the value of file_comment.file_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getFile_id() {
        return file_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.file_id
     *
     * @param file_id the value for file_comment.file_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setFile_id(Long file_id) {
        this.file_id = file_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.user_id
     *
     * @return the value of file_comment.user_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.user_id
     *
     * @param user_id the value for file_comment.user_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.content
     *
     * @return the value of file_comment.content
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.content
     *
     * @param content the value for file_comment.content
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.is_callback
     *
     * @return the value of file_comment.is_callback
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Byte getIs_callback() {
        return is_callback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.is_callback
     *
     * @param is_callback the value for file_comment.is_callback
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setIs_callback(Byte is_callback) {
        this.is_callback = is_callback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.callback_id
     *
     * @return the value of file_comment.callback_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getCallback_id() {
        return callback_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.callback_id
     *
     * @param callback_id the value for file_comment.callback_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setCallback_id(Long callback_id) {
        this.callback_id = callback_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.agree
     *
     * @return the value of file_comment.agree
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Integer getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.agree
     *
     * @param agree the value for file_comment.agree
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setAgree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.disagree
     *
     * @return the value of file_comment.disagree
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Integer getDisagree() {
        return disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.disagree
     *
     * @param disagree the value for file_comment.disagree
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setDisagree(Integer disagree) {
        this.disagree = disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_comment.comment_time
     *
     * @return the value of file_comment.comment_time
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Date getComment_time() {
        return comment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_comment.comment_time
     *
     * @param comment_time the value for file_comment.comment_time
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setComment_time(Date comment_time) {
        this.comment_time = comment_time;
    }
    public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	public Byte getScore() {
		return score;
	}

	public void setScore(Byte score) {
		this.score = score;
	}
	public Byte getStatus() {
		return status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
	private User user;
}