package cn.bnsr.edu_yun.frontstage.resource.po;

public class File_value {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_value.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_value.file_amount
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long file_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_value.file_score
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long file_score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_value.id
     *
     * @return the value of file_value.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_value.id
     *
     * @param id the value for file_value.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_value.file_amount
     *
     * @return the value of file_value.file_amount
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getFile_amount() {
        return file_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_value.file_amount
     *
     * @param file_amount the value for file_value.file_amount
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setFile_amount(Long file_amount) {
        this.file_amount = file_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_value.file_score
     *
     * @return the value of file_value.file_score
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getFile_score() {
        return file_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_value.file_score
     *
     * @param file_score the value for file_value.file_score
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setFile_score(Long file_score) {
        this.file_score = file_score;
    }
}