package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class Workshop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.name
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.profile
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.img
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String img;

    private String img_name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.period
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.subject
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.is_top
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Integer is_top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.community_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long community_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.status
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.user_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workshop.create_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Date create_time;
    
    private Integer is_default_img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.id
     *
     * @return the value of workshop.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.id
     *
     * @param id the value for workshop.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.name
     *
     * @return the value of workshop.name
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.name
     *
     * @param name the value for workshop.name
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.profile
     *
     * @return the value of workshop.profile
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.profile
     *
     * @param profile the value for workshop.profile
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.img
     *
     * @return the value of workshop.img
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.img
     *
     * @param img the value for workshop.img
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setImg(String img) {
        this.img = img;
    }

    public String getImg_name() {
		return img_name;
	}

	public void setImg_name(String img_name) {
		this.img_name = img_name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.period
     *
     * @return the value of workshop.period
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.period
     *
     * @param period the value for workshop.period
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.subject
     *
     * @return the value of workshop.subject
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.subject
     *
     * @param subject the value for workshop.subject
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.is_top
     *
     * @return the value of workshop.is_top
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Integer getIs_top() {
        return is_top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.is_top
     *
     * @param is_top the value for workshop.is_top
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setIs_top(Integer is_top) {
        this.is_top = is_top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.community_id
     *
     * @return the value of workshop.community_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getCommunity_id() {
        return community_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.community_id
     *
     * @param community_id the value for workshop.community_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setCommunity_id(Long community_id) {
        this.community_id = community_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.status
     *
     * @return the value of workshop.status
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.status
     *
     * @param status the value for workshop.status
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.user_id
     *
     * @return the value of workshop.user_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.user_id
     *
     * @param user_id the value for workshop.user_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workshop.create_time
     *
     * @return the value of workshop.create_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workshop.create_time
     *
     * @param create_time the value for workshop.create_time
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

	public Integer getIs_default_img() {
		return is_default_img;
	}

	public void setIs_default_img(Integer is_default_img) {
		this.is_default_img = is_default_img;
	}
    
}