package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.train.po.ClassBelongs;
import cn.bnsr.edu_yun.frontstage.train.view.CommunityCourseView;
import cn.bnsr.edu_yun.frontstage.train.view.CommunityTrainView;
import cn.bnsr.edu_yun.frontstage.train.view.DataStatsView;

public interface ClassBelongsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_belongs
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_belongs
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	int insert(ClassBelongs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_belongs
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	int insertSelective(ClassBelongs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_belongs
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	ClassBelongs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_belongs
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	int updateByPrimaryKeySelective(ClassBelongs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_belongs
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	int updateByPrimaryKey(ClassBelongs record);
	
	ClassBelongs selectClassBelongsByClassId(Long classId);
	
	List<CommunityCourseView> queryCommunityCourses(CommunityCourseView communityCourseView);
	
	List<CommunityTrainView> queryCommunityTarins(CommunityTrainView communityTrainView);
	
	int queryCommunityCoursesTotal(CommunityCourseView communityCourseView);
	
	int queryCommunityTarinsTotal(CommunityTrainView communityTrainView);
	
	void updateStatus(@Param("id")long id,@Param("status")int status);

	List<DataStatsView> classBelongsDataStats(DataStatsView dataStatsView);
}