package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.base.po.Label;
import cn.bnsr.edu_yun.frontstage.train.po.CourseLabelRelation;

public interface CourseLabelRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label_relation
     *
     * @mbggenerated Thu Oct 27 14:30:11 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label_relation
     *
     * @mbggenerated Thu Oct 27 14:30:11 CST 2016
     */
    int insert(CourseLabelRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label_relation
     *
     * @mbggenerated Thu Oct 27 14:30:11 CST 2016
     */
    int insertSelective(CourseLabelRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label_relation
     *
     * @mbggenerated Thu Oct 27 14:30:11 CST 2016
     */
    CourseLabelRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label_relation
     *
     * @mbggenerated Thu Oct 27 14:30:11 CST 2016
     */
    int updateByPrimaryKeySelective(CourseLabelRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label_relation
     *
     * @mbggenerated Thu Oct 27 14:30:11 CST 2016
     */
    int updateByPrimaryKey(CourseLabelRelation record);

	List<Label> getByCourseId(Long courseId);
 
	void deleteCourseRelation(Long courseId);
}