package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.status
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classes
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String classes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.end_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.maximum
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer maximum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.continue_study
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer continue_study;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.type
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.complete_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date complete_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.discount
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.is_abandon
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer is_abandon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.refund_condition
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer refund_condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.sign_up
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer sign_up;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.credit
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.close_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date close_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date open_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long classify_id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date create_time;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.is_refund
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer is_refund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.status
     *
     * @return the value of class.status
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.status
     *
     * @param status the value for class.status
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classes
     *
     * @return the value of class.classes
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classes
     *
     * @param classes the value for class.classes
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.end_time
     *
     * @return the value of class.end_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.end_time
     *
     * @param end_time the value for class.end_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.maximum
     *
     * @return the value of class.maximum
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getMaximum() {
        return maximum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.maximum
     *
     * @param maximum the value for class.maximum
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setMaximum(Integer maximum) {
        this.maximum = maximum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.continue_study
     *
     * @return the value of class.continue_study
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getContinue_study() {
        return continue_study;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.continue_study
     *
     * @param continue_study the value for class.continue_study
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setContinue_study(Integer continue_study) {
        this.continue_study = continue_study;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.type
     *
     * @return the value of class.type
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.type
     *
     * @param type the value for class.type
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.complete_time
     *
     * @return the value of class.complete_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getComplete_time() {
        return complete_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.complete_time
     *
     * @param complete_time the value for class.complete_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setComplete_time(Date complete_time) {
        this.complete_time = complete_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.discount
     *
     * @return the value of class.discount
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.discount
     *
     * @param discount the value for class.discount
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.is_abandon
     *
     * @return the value of class.is_abandon
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getIs_abandon() {
        return is_abandon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.is_abandon
     *
     * @param is_abandon the value for class.is_abandon
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setIs_abandon(Integer is_abandon) {
        this.is_abandon = is_abandon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.refund_condition
     *
     * @return the value of class.refund_condition
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getRefund_condition() {
        return refund_condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.refund_condition
     *
     * @param refund_condition the value for class.refund_condition
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setRefund_condition(Integer refund_condition) {
        this.refund_condition = refund_condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.sign_up
     *
     * @return the value of class.sign_up
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getSign_up() {
        return sign_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.sign_up
     *
     * @param sign_up the value for class.sign_up
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setSign_up(Integer sign_up) {
        this.sign_up = sign_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.price
     *
     * @return the value of class.price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.price
     *
     * @param price the value for class.price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.credit
     *
     * @return the value of class.credit
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.credit
     *
     * @param credit the value for class.credit
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.close_time
     *
     * @return the value of class.close_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getClose_time() {
        return close_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.close_time
     *
     * @param close_time the value for class.close_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setClose_time(Date close_time) {
        this.close_time = close_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.open_time
     *
     * @return the value of class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getOpen_time() {
        return open_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.open_time
     *
     * @param open_time the value for class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setOpen_time(Date open_time) {
        this.open_time = open_time;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.open_time
     *
     * @param open_time the value for class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
	public Long getClassify_id() {
		return classify_id;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.open_time
     *
     * @param open_time the value for class.open_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
	public void setClassify_id(Long classify_id) {
		this.classify_id = classify_id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.create_time
     *
     * @param open_time the value for class.create_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
	public Date getCreate_time() {
		return create_time;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.create_time
     *
     * @param open_time the value for class.create_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Integer getIs_refund() {
		return is_refund;
	}

	public void setIs_refund(Integer is_refund) {
		this.is_refund = is_refund;
	}

}