package cn.bnsr.edu_yun.frontstage.xbjy.po;

public class LessonUserTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_task.id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_task.lesson_id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    private Long lesson_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_task.user_id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_task.purview
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    private Integer purview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_task.status
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_task.id
     *
     * @return the value of lesson_user_task.id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_task.id
     *
     * @param id the value for lesson_user_task.id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_task.lesson_id
     *
     * @return the value of lesson_user_task.lesson_id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public Long getLesson_id() {
        return lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_task.lesson_id
     *
     * @param lesson_id the value for lesson_user_task.lesson_id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public void setLesson_id(Long lesson_id) {
        this.lesson_id = lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_task.user_id
     *
     * @return the value of lesson_user_task.user_id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_task.user_id
     *
     * @param user_id the value for lesson_user_task.user_id
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_task.purview
     *
     * @return the value of lesson_user_task.purview
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public Integer getPurview() {
        return purview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_task.purview
     *
     * @param purview the value for lesson_user_task.purview
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public void setPurview(Integer purview) {
        this.purview = purview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_task.status
     *
     * @return the value of lesson_user_task.status
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_task.status
     *
     * @param status the value for lesson_user_task.status
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}