package cn.bnsr.edu_yun.frontstage.xbjy.po;

public class LessonUserIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_identity.id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_identity.lesson_id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    private Long lesson_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_identity.user_id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_user_identity.Identity
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    private Integer identity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_identity.id
     *
     * @return the value of lesson_user_identity.id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_identity.id
     *
     * @param id the value for lesson_user_identity.id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_identity.lesson_id
     *
     * @return the value of lesson_user_identity.lesson_id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public Long getLesson_id() {
        return lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_identity.lesson_id
     *
     * @param lesson_id the value for lesson_user_identity.lesson_id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public void setLesson_id(Long lesson_id) {
        this.lesson_id = lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_identity.user_id
     *
     * @return the value of lesson_user_identity.user_id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_identity.user_id
     *
     * @param user_id the value for lesson_user_identity.user_id
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_user_identity.Identity
     *
     * @return the value of lesson_user_identity.Identity
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public Integer getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_user_identity.Identity
     *
     * @param identity the value for lesson_user_identity.Identity
     *
     * @mbggenerated Mon Mar 13 11:20:25 CST 2017
     */
    public void setIdentity(Integer identity) {
        this.identity = identity;
    }
}