package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class UserStudyTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.user_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.course_hour_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Long course_hour_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.class_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Long class_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.start_time
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Date start_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.study_time
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Long study_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_study_time.duration
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    private Long duration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.id
     *
     * @return the value of user_study_time.id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.id
     *
     * @param id the value for user_study_time.id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.user_id
     *
     * @return the value of user_study_time.user_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.user_id
     *
     * @param user_id the value for user_study_time.user_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.course_hour_id
     *
     * @return the value of user_study_time.course_hour_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Long getCourse_hour_id() {
        return course_hour_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.course_hour_id
     *
     * @param course_hour_id the value for user_study_time.course_hour_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setCourse_hour_id(Long course_hour_id) {
        this.course_hour_id = course_hour_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.class_id
     *
     * @return the value of user_study_time.class_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.class_id
     *
     * @param class_id the value for user_study_time.class_id
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.start_time
     *
     * @return the value of user_study_time.start_time
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.start_time
     *
     * @param start_time the value for user_study_time.start_time
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.study_time
     *
     * @return the value of user_study_time.study_time
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Long getStudy_time() {
        return study_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.study_time
     *
     * @param study_time the value for user_study_time.study_time
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setStudy_time(Long study_time) {
        this.study_time = study_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_study_time.duration
     *
     * @return the value of user_study_time.duration
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_study_time.duration
     *
     * @param duration the value for user_study_time.duration
     *
     * @mbggenerated Thu Sep 07 16:27:02 CST 2017
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }
}