package cn.bnsr.edu_yun.frontstage.resource.mapper;

import cn.bnsr.edu_yun.frontstage.resource.po.File_value;

public interface File_valueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_value
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_value
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insert(File_value record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_value
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insertSelective(File_value record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_value
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    File_value selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_value
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKeySelective(File_value record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_value
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKey(File_value record);
}