package cn.bnsr.edu_yun.frontstage.train.service;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.train.po.Plan;
import cn.bnsr.edu_yun.frontstage.train.view.PlanView;

public interface PlanService {
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);
    
    void batchDeleteByPrimaryKey(long[] ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    Plan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int updateByPrimaryKey(Plan record);
    
	/** 根据社区id&计划名称查询计划列表 */
    public List<Plan> queryPlansbyComId(PlanView planView);

    void updatePlanStatus(long id,int status);
    
    void batchUpdatePlanStatus(long[] ids,int status);

    int queryPlanTotalbyComId(PlanView planView);
}
