package cn.bnsr.edu_yun.frontstage.xbjy.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.xbjy.po.LessonUserTask;
import cn.bnsr.edu_yun.frontstage.xbjy.view.LessonUserTaskView;

public interface LessonUserTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_user_task
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_user_task
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    int insert(LessonUserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_user_task
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    int insertSelective(LessonUserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_user_task
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    LessonUserTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_user_task
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    int updateByPrimaryKeySelective(LessonUserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_user_task
     *
     * @mbggenerated Mon Mar 27 13:50:07 CST 2017
     */
    int updateByPrimaryKey(LessonUserTask record);
    
    LessonUserTaskView findByLUP(LessonUserTaskView lessonUserTaskView);
    
    List<LessonUserTaskView> findUserByLesson(LessonUserTaskView lessonUserTaskView);
    
    List<LessonUserTaskView> findPurview(LessonUserTaskView lessonUserTaskView);
    
    Integer countTask(LessonUserTaskView lessonUserTaskView);
    
    List<LessonUserTaskView> findByPurview(LessonUserTaskView lessonUserTaskView);
}