package cn.bnsr.edu_yun.frontstage.xbjy.mapper;

import cn.bnsr.edu_yun.frontstage.xbjy.po.LessonTime;
import cn.bnsr.edu_yun.frontstage.xbjy.view.LessonTimeView;

public interface LessonTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_time
     *
     * @mbggenerated Mon Mar 27 10:17:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_time
     *
     * @mbggenerated Mon Mar 27 10:17:36 CST 2017
     */
    int insert(LessonTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_time
     *
     * @mbggenerated Mon Mar 27 10:17:36 CST 2017
     */
    int insertSelective(LessonTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_time
     *
     * @mbggenerated Mon Mar 27 10:17:36 CST 2017
     */
    LessonTime selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_time
     *
     * @mbggenerated Mon Mar 27 10:17:36 CST 2017
     */
    int updateByPrimaryKeySelective(LessonTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_time
     *
     * @mbggenerated Mon Mar 27 10:17:36 CST 2017
     */
    int updateByPrimaryKey(LessonTime record);
    
    void updateByLesssonId(LessonTimeView lessonTimeView);
    
    LessonTimeView findByLesson(Long lesson_id);
}