package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class Recommended {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommended.id
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommended.source_type
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	private Integer source_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommended.source_id
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	private Long source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommended.seq
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	private Long seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommended.recommended_time
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	private Date recommended_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommended.valid_time
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	private Date valid_time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommended.id
	 * @return  the value of recommended.id
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommended.id
	 * @param id  the value for recommended.id
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommended.source_type
	 * @return  the value of recommended.source_type
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public Integer getSource_type() {
		return source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommended.source_type
	 * @param source_type  the value for recommended.source_type
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public void setSource_type(Integer source_type) {
		this.source_type = source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommended.source_id
	 * @return  the value of recommended.source_id
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public Long getSource_id() {
		return source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommended.source_id
	 * @param source_id  the value for recommended.source_id
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public void setSource_id(Long source_id) {
		this.source_id = source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommended.seq
	 * @return  the value of recommended.seq
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public Long getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommended.seq
	 * @param seq  the value for recommended.seq
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public void setSeq(Long seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommended.recommended_time
	 * @return  the value of recommended.recommended_time
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public Date getRecommended_time() {
		return recommended_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommended.recommended_time
	 * @param recommended_time  the value for recommended.recommended_time
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public void setRecommended_time(Date recommended_time) {
		this.recommended_time = recommended_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommended.valid_time
	 * @return  the value of recommended.valid_time
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public Date getValid_time() {
		return valid_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommended.valid_time
	 * @param valid_time  the value for recommended.valid_time
	 * @mbggenerated  Tue Dec 20 14:54:20 CST 2016
	 */
	public void setValid_time(Date valid_time) {
		this.valid_time = valid_time;
	}
}