package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class ClassBelongs {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_belongs.id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_belongs.class_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	private Long class_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_belongs.source_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	private Long source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_belongs.source_type
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	private Integer source_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_belongs.classify_relation_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	private Long classify_relation_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_belongs.status
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	private Integer status;
	
	private Date create_time;
	
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_belongs.id
	 * @return  the value of class_belongs.id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_belongs.id
	 * @param id  the value for class_belongs.id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_belongs.class_id
	 * @return  the value of class_belongs.class_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public Long getClass_id() {
		return class_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_belongs.class_id
	 * @param class_id  the value for class_belongs.class_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public void setClass_id(Long class_id) {
		this.class_id = class_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_belongs.source_id
	 * @return  the value of class_belongs.source_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public Long getSource_id() {
		return source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_belongs.source_id
	 * @param source_id  the value for class_belongs.source_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public void setSource_id(Long source_id) {
		this.source_id = source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_belongs.source_type
	 * @return  the value of class_belongs.source_type
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public Integer getSource_type() {
		return source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_belongs.source_type
	 * @param source_type  the value for class_belongs.source_type
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public void setSource_type(Integer source_type) {
		this.source_type = source_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_belongs.classify_relation_id
	 * @return  the value of class_belongs.classify_relation_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public Long getClassify_relation_id() {
		return classify_relation_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_belongs.classify_relation_id
	 * @param classify_relation_id  the value for class_belongs.classify_relation_id
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public void setClassify_relation_id(Long classify_relation_id) {
		this.classify_relation_id = classify_relation_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_belongs.status
	 * @return  the value of class_belongs.status
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_belongs.status
	 * @param status  the value for class_belongs.status
	 * @mbggenerated  Fri May 19 11:07:06 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public Date getCreate_time() {
		return create_time;
	}
	
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	
	public Integer getType() {
		return type;
	}
	
	public void setType(Integer type) {
		this.type = type;
	}
}