package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class UserAppraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.source_id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Long source_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.user_id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.score
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Byte score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.appraise_time
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Date appraise_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.status
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.source_type
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private Integer source_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_appraise.appraise_content
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    private String appraise_content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.id
     *
     * @return the value of user_appraise.id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.id
     *
     * @param id the value for user_appraise.id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.source_id
     *
     * @return the value of user_appraise.source_id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Long getSource_id() {
        return source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.source_id
     *
     * @param source_id the value for user_appraise.source_id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setSource_id(Long source_id) {
        this.source_id = source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.user_id
     *
     * @return the value of user_appraise.user_id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.user_id
     *
     * @param user_id the value for user_appraise.user_id
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.score
     *
     * @return the value of user_appraise.score
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.score
     *
     * @param score the value for user_appraise.score
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.appraise_time
     *
     * @return the value of user_appraise.appraise_time
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Date getAppraise_time() {
        return appraise_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.appraise_time
     *
     * @param appraise_time the value for user_appraise.appraise_time
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setAppraise_time(Date appraise_time) {
        this.appraise_time = appraise_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.status
     *
     * @return the value of user_appraise.status
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.status
     *
     * @param status the value for user_appraise.status
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.source_type
     *
     * @return the value of user_appraise.source_type
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public Integer getSource_type() {
        return source_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.source_type
     *
     * @param source_type the value for user_appraise.source_type
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setSource_type(Integer source_type) {
        this.source_type = source_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_appraise.appraise_content
     *
     * @return the value of user_appraise.appraise_content
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public String getAppraise_content() {
        return appraise_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_appraise.appraise_content
     *
     * @param appraise_content the value for user_appraise.appraise_content
     *
     * @mbggenerated Thu Jan 19 09:40:07 CST 2017
     */
    public void setAppraise_content(String appraise_content) {
        this.appraise_content = appraise_content;
    }
}