package cn.bnsr.edu_yun.frontstage.base.mapper;

import cn.bnsr.edu_yun.frontstage.base.po.UserSupport;

public interface UserSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated Wed Aug 31 13:24:46 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated Wed Aug 31 13:24:46 CST 2016
     */
    int insert(UserSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated Wed Aug 31 13:24:46 CST 2016
     */
    int insertSelective(UserSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated Wed Aug 31 13:24:46 CST 2016
     */
    UserSupport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated Wed Aug 31 13:24:46 CST 2016
     */
    int updateByPrimaryKeySelective(UserSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_support
     *
     * @mbggenerated Wed Aug 31 13:24:46 CST 2016
     */
    int updateByPrimaryKey(UserSupport record);
    
    UserSupport showUserSupport(UserSupport userSupport);
}