package cn.bnsr.edu_yun.frontstage.resource.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.resource.po.File_comment;

public interface File_commentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_comment
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_comment
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insert(File_comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_comment
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insertSelective(File_comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_comment
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    File_comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_comment
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKeySelective(File_comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_comment
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKey(File_comment record);
    
    List<File_comment> selectCommentByFileId(long file_id);
    List<File_comment> selectCommentByFileIdAndUserId(@Param("file_id")long file_id,@Param("user_id")long user_id);
    List<File_comment> selectCommentByFileIdAll(@Param("file_id")long file_id,@Param("status")Integer status,@Param("start")long start,@Param("pageSize")long pageSize);
    int selectCountByFile(@Param("file_id")long file_id,@Param("status")Integer status);
}