package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class UserDurationPart {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.start_time
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Date start_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.end_time
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Date end_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.total_ms
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Long total_ms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.user_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.device
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Integer device;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.province_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private String province_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.address
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_duration_part.part_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	private Long part_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.id
	 * @return  the value of user_duration_part.id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.id
	 * @param id  the value for user_duration_part.id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.start_time
	 * @return  the value of user_duration_part.start_time
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Date getStart_time() {
		return start_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.start_time
	 * @param start_time  the value for user_duration_part.start_time
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.end_time
	 * @return  the value of user_duration_part.end_time
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Date getEnd_time() {
		return end_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.end_time
	 * @param end_time  the value for user_duration_part.end_time
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setEnd_time(Date end_time) {
		this.end_time = end_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.total_ms
	 * @return  the value of user_duration_part.total_ms
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Long getTotal_ms() {
		return total_ms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.total_ms
	 * @param total_ms  the value for user_duration_part.total_ms
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setTotal_ms(Long total_ms) {
		this.total_ms = total_ms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.user_id
	 * @return  the value of user_duration_part.user_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.user_id
	 * @param user_id  the value for user_duration_part.user_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.device
	 * @return  the value of user_duration_part.device
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Integer getDevice() {
		return device;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.device
	 * @param device  the value for user_duration_part.device
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setDevice(Integer device) {
		this.device = device;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.province_id
	 * @return  the value of user_duration_part.province_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public String getProvince_id() {
		return province_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.province_id
	 * @param province_id  the value for user_duration_part.province_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setProvince_id(String province_id) {
		this.province_id = province_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.address
	 * @return  the value of user_duration_part.address
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.address
	 * @param address  the value for user_duration_part.address
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_duration_part.part_id
	 * @return  the value of user_duration_part.part_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public Long getPart_id() {
		return part_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_duration_part.part_id
	 * @param part_id  the value for user_duration_part.part_id
	 * @mbggenerated  Fri Oct 13 17:04:05 CST 2017
	 */
	public void setPart_id(Long part_id) {
		this.part_id = part_id;
	}
}