package cn.bnsr.edu_yun.frontstage.resource.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.resource.po.User_file_log;

public interface User_file_logMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_log
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_log
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insert(User_file_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_log
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insertSelective(User_file_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_log
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    User_file_log selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_log
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKeySelective(User_file_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_log
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKey(User_file_log record);
    
    List<Long> selectDistinctUser(@Param("str")String str);
    
    List<User_file_log> selectByUserId(@Param("str")String str,@Param("user_id")long user_id);
}