package cn.bnsr.edu_yun.frontstage.base.po;

public class Search {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.search_name
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private String search_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search.search_times
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Integer search_times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.id
     *
     * @return the value of search.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.id
     *
     * @param id the value for search.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.search_name
     *
     * @return the value of search.search_name
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public String getSearch_name() {
        return search_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.search_name
     *
     * @param search_name the value for search.search_name
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setSearch_name(String search_name) {
        this.search_name = search_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search.search_times
     *
     * @return the value of search.search_times
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Integer getSearch_times() {
        return search_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search.search_times
     *
     * @param search_times the value for search.search_times
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setSearch_times(Integer search_times) {
        this.search_times = search_times;
    }
}