package cn.bnsr.edu_yun.frontstage.train.mapper;

import cn.bnsr.edu_yun.frontstage.train.po.ClassRelation;

public interface ClassRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_relation
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_relation
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int insert(ClassRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_relation
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int insertSelective(ClassRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_relation
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    ClassRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_relation
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int updateByPrimaryKeySelective(ClassRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_relation
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int updateByPrimaryKey(ClassRelation record);
    
    Long getLastId();
    
    ClassRelation getByClassId(Long class_id);
}