package cn.bnsr.edu_yun.frontstage.base.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.backstage.base.view.ClassifyView;
import cn.bnsr.edu_yun.frontstage.base.po.Classify;

public interface ClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    int insert(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    int insertSelective(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    Classify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    int updateByPrimaryKeySelective(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    int updateByPrimaryKey(Classify record);
    
    public List<Classify> selectAnyOne(Classify classify);

	List<Classify> findAllClassify(@Param("type")int type,@Param("flag")boolean flag);

	public List<Classify> find(ClassifyView classifyView);

	public Long count(ClassifyView classifyView);
	
	/**
	 * 
	 * TODO 展示树形数据
	 * @param menu
	 * @return
	 */
	public List<ClassifyView> queryTreeGrid(Classify classify);
	
	/*
	 * 统计子节点数
	 */
	public Long countChildren(String parent_id);
	
	public List<Classify> queryTree(Classify classify);

	List<Classify> queryByParentId(Long classifyId);
	
	Long getIdByName(String classify_name);
	
	ClassifyView getClassifyViewById(int id);
	
	List<cn.bnsr.edu_yun.frontstage.base.view.ClassifyView> queryViewByParentId(Long classifyId);
	
	String getLastType();
}