package cn.bnsr.edu_yun.frontstage.train.mapper;

import cn.bnsr.edu_yun.frontstage.train.po.MessageFile;

public interface MessageFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_file
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_file
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int insert(MessageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_file
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int insertSelective(MessageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_file
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    MessageFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_file
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int updateByPrimaryKeySelective(MessageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_file
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int updateByPrimaryKey(MessageFile record);
    
    void deleteByMessageId(long id);
}