package cn.bnsr.edu_yun.backstage.base.po;

import java.util.Date;

public class SysLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.user_name
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String user_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.user_id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.log_type
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private Integer log_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.do_url
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String do_url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.do_from
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String do_from;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.create_time
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private Date create_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.local_ip
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String local_ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.remote_ip
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String remote_ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.browser
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String browser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.sys_name
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String sys_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.do_id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private Long do_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.do_type
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private Integer do_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.msg
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	private String msg;
	
	private String address;
	
	private Integer device;
	
	private String province_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.id
	 * @return  the value of sys_log.id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.id
	 * @param id  the value for sys_log.id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.user_name
	 * @return  the value of sys_log.user_name
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.user_name
	 * @param user_name  the value for sys_log.user_name
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.user_id
	 * @return  the value of sys_log.user_id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.user_id
	 * @param user_id  the value for sys_log.user_id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.log_type
	 * @return  the value of sys_log.log_type
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public Integer getLog_type() {
		return log_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.log_type
	 * @param log_type  the value for sys_log.log_type
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setLog_type(Integer log_type) {
		this.log_type = log_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.do_url
	 * @return  the value of sys_log.do_url
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getDo_url() {
		return do_url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.do_url
	 * @param do_url  the value for sys_log.do_url
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setDo_url(String do_url) {
		this.do_url = do_url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.do_from
	 * @return  the value of sys_log.do_from
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getDo_from() {
		return do_from;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.do_from
	 * @param do_from  the value for sys_log.do_from
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setDo_from(String do_from) {
		this.do_from = do_from;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.create_time
	 * @return  the value of sys_log.create_time
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.create_time
	 * @param create_time  the value for sys_log.create_time
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.local_ip
	 * @return  the value of sys_log.local_ip
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getLocal_ip() {
		return local_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.local_ip
	 * @param local_ip  the value for sys_log.local_ip
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setLocal_ip(String local_ip) {
		this.local_ip = local_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.remote_ip
	 * @return  the value of sys_log.remote_ip
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getRemote_ip() {
		return remote_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.remote_ip
	 * @param remote_ip  the value for sys_log.remote_ip
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setRemote_ip(String remote_ip) {
		this.remote_ip = remote_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.browser
	 * @return  the value of sys_log.browser
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getBrowser() {
		return browser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.browser
	 * @param browser  the value for sys_log.browser
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setBrowser(String browser) {
		this.browser = browser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.sys_name
	 * @return  the value of sys_log.sys_name
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getSys_name() {
		return sys_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.sys_name
	 * @param sys_name  the value for sys_log.sys_name
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setSys_name(String sys_name) {
		this.sys_name = sys_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.do_id
	 * @return  the value of sys_log.do_id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public Long getDo_id() {
		return do_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.do_id
	 * @param do_id  the value for sys_log.do_id
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setDo_id(Long do_id) {
		this.do_id = do_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.do_type
	 * @return  the value of sys_log.do_type
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public Integer getDo_type() {
		return do_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.do_type
	 * @param do_type  the value for sys_log.do_type
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setDo_type(Integer do_type) {
		this.do_type = do_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.msg
	 * @return  the value of sys_log.msg
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public String getMsg() {
		return msg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.msg
	 * @param msg  the value for sys_log.msg
	 * @mbggenerated  Tue Jun 27 10:43:27 CST 2017
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getDevice() {
		return device;
	}

	public void setDevice(Integer device) {
		this.device = device;
	}

	public String getProvince_id() {
		return province_id;
	}

	public void setProvince_id(String province_id) {
		this.province_id = province_id;
	}
	
}