package cn.bnsr.edu_yun.frontstage.tiku.mapper;

import cn.bnsr.edu_yun.frontstage.tiku.po.QuestionCollection;

public interface QuestionCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_collection
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_collection
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int insert(QuestionCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_collection
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int insertSelective(QuestionCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_collection
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    QuestionCollection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_collection
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int updateByPrimaryKeySelective(QuestionCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_collection
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int updateByPrimaryKey(QuestionCollection record);
}