package cn.bnsr.edu_yun.frontstage.resource.po;

import java.util.Date;

public class User_file {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Long file_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.type
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.time
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    private Date time;

    private Integer file_type;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.id
     *
     * @return the value of user_file.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.id
     *
     * @param id the value for user_file.id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_id
     *
     * @return the value of user_file.user_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_id
     *
     * @param user_id the value for user_file.user_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_id
     *
     * @return the value of user_file.file_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Long getFile_id() {
        return file_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_id
     *
     * @param file_id the value for user_file.file_id
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setFile_id(Long file_id) {
        this.file_id = file_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.type
     *
     * @return the value of user_file.type
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.type
     *
     * @param type the value for user_file.type
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.time
     *
     * @return the value of user_file.time
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.time
     *
     * @param time the value for user_file.time
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

	public Integer getFile_type() {
		return file_type;
	}

	public void setFile_type(Integer file_type) {
		this.file_type = file_type;
	}
    
}