package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class AppraiseReason {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise_reason.id
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise_reason.title
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise_reason.create_time
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise_reason.level
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise_reason.update_time
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    private Date update_time;

    private Integer type;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise_reason.id
     *
     * @return the value of appraise_reason.id
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise_reason.id
     *
     * @param id the value for appraise_reason.id
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise_reason.title
     *
     * @return the value of appraise_reason.title
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise_reason.title
     *
     * @param title the value for appraise_reason.title
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise_reason.create_time
     *
     * @return the value of appraise_reason.create_time
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise_reason.create_time
     *
     * @param create_time the value for appraise_reason.create_time
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise_reason.level
     *
     * @return the value of appraise_reason.level
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise_reason.level
     *
     * @param level the value for appraise_reason.level
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise_reason.update_time
     *
     * @return the value of appraise_reason.update_time
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise_reason.update_time
     *
     * @param update_time the value for appraise_reason.update_time
     *
     * @mbggenerated Sun Sep 24 17:06:18 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
}