package cn.bnsr.edu_yun.frontstage.base.po;

public class Area {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.id
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.area_name
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private String area_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.parentId
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.vNo
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private Integer vNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.area_id
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private String area_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.area_parentid
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private String area_parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.count
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	private Integer count;
	
	private Integer is_open;//项目是否在该地区开放：0--是；1--否；

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.id
	 * @return  the value of area.id
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.id
	 * @param id  the value for area.id
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.area_name
	 * @return  the value of area.area_name
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public String getArea_name() {
		return area_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.area_name
	 * @param area_name  the value for area.area_name
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setArea_name(String area_name) {
		this.area_name = area_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.parentId
	 * @return  the value of area.parentId
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.parentId
	 * @param parentId  the value for area.parentId
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.vNo
	 * @return  the value of area.vNo
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public Integer getvNo() {
		return vNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.vNo
	 * @param vNo  the value for area.vNo
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setvNo(Integer vNo) {
		this.vNo = vNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.area_id
	 * @return  the value of area.area_id
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public String getArea_id() {
		return area_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.area_id
	 * @param area_id  the value for area.area_id
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setArea_id(String area_id) {
		this.area_id = area_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.area_parentid
	 * @return  the value of area.area_parentid
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public String getArea_parentid() {
		return area_parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.area_parentid
	 * @param area_parentid  the value for area.area_parentid
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setArea_parentid(String area_parentid) {
		this.area_parentid = area_parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.count
	 * @return  the value of area.count
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.count
	 * @param count  the value for area.count
	 * @mbggenerated  Wed Aug 31 16:48:34 CST 2016
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getIs_open() {
		return is_open;
	}

	public void setIs_open(Integer is_open) {
		this.is_open = is_open;
	}
	
	
}