package cn.bnsr.edu_yun.frontstage.base.po;

public class BookCat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.id
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.parent_id
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private String parent_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.versionId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private String versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.bookCatelogId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private String bookCatelogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.bookCatelogName
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private String bookCatelogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.parentId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.seqNo
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private Integer seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_cat.vNo
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    private Integer vNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.id
     *
     * @return the value of book_cat.id
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.id
     *
     * @param id the value for book_cat.id
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.parent_id
     *
     * @return the value of book_cat.parent_id
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public String getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.parent_id
     *
     * @param parent_id the value for book_cat.parent_id
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setParent_id(String parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.versionId
     *
     * @return the value of book_cat.versionId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.versionId
     *
     * @param versionId the value for book_cat.versionId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.bookCatelogId
     *
     * @return the value of book_cat.bookCatelogId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public String getBookCatelogId() {
        return bookCatelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.bookCatelogId
     *
     * @param bookCatelogId the value for book_cat.bookCatelogId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setBookCatelogId(String bookCatelogId) {
        this.bookCatelogId = bookCatelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.bookCatelogName
     *
     * @return the value of book_cat.bookCatelogName
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public String getBookCatelogName() {
        return bookCatelogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.bookCatelogName
     *
     * @param bookCatelogName the value for book_cat.bookCatelogName
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setBookCatelogName(String bookCatelogName) {
        this.bookCatelogName = bookCatelogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.parentId
     *
     * @return the value of book_cat.parentId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.parentId
     *
     * @param parentId the value for book_cat.parentId
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.seqNo
     *
     * @return the value of book_cat.seqNo
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.seqNo
     *
     * @param seqNo the value for book_cat.seqNo
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_cat.vNo
     *
     * @return the value of book_cat.vNo
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public Integer getvNo() {
        return vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_cat.vNo
     *
     * @param vNo the value for book_cat.vNo
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    public void setvNo(Integer vNo) {
        this.vNo = vNo;
    }
}