package cn.bnsr.edu_yun.frontstage.base.po;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Thu Sep 08 13:27:10 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_name
     *
     * @mbggenerated Thu Sep 08 13:27:10 CST 2016
     */
    private String grade_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Thu Sep 08 13:27:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Thu Sep 08 13:27:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_name
     *
     * @return the value of grade.grade_name
     *
     * @mbggenerated Thu Sep 08 13:27:10 CST 2016
     */
    public String getGrade_name() {
        return grade_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_name
     *
     * @param grade_name the value for grade.grade_name
     *
     * @mbggenerated Thu Sep 08 13:27:10 CST 2016
     */
    public void setGrade_name(String grade_name) {
        this.grade_name = grade_name;
    }
}