package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.user_id
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.type
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.message
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.time
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.user_id
     *
     * @return the value of notice.user_id
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.user_id
     *
     * @param user_id the value for notice.user_id
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.type
     *
     * @return the value of notice.type
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.type
     *
     * @param type the value for notice.type
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.message
     *
     * @return the value of notice.message
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.message
     *
     * @param message the value for notice.message
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.time
     *
     * @return the value of notice.time
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.time
     *
     * @param time the value for notice.time
     *
     * @mbggenerated Sun Sep 18 14:44:13 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }
}