package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class OrderPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.id
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_id
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private Long order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_account
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private String pay_account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_type
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private Integer pay_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_user_ip
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private String pay_user_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_status
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private Integer pay_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_msg
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private String pay_msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_time
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    private Date pay_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.id
     *
     * @return the value of order_pay.id
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.id
     *
     * @param id the value for order_pay.id
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_id
     *
     * @return the value of order_pay.order_id
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public Long getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_id
     *
     * @param order_id the value for order_pay.order_id
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setOrder_id(Long order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_account
     *
     * @return the value of order_pay.pay_account
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public String getPay_account() {
        return pay_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_account
     *
     * @param pay_account the value for order_pay.pay_account
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setPay_account(String pay_account) {
        this.pay_account = pay_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_type
     *
     * @return the value of order_pay.pay_type
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public Integer getPay_type() {
        return pay_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_type
     *
     * @param pay_type the value for order_pay.pay_type
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setPay_type(Integer pay_type) {
        this.pay_type = pay_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_user_ip
     *
     * @return the value of order_pay.pay_user_ip
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public String getPay_user_ip() {
        return pay_user_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_user_ip
     *
     * @param pay_user_ip the value for order_pay.pay_user_ip
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setPay_user_ip(String pay_user_ip) {
        this.pay_user_ip = pay_user_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_status
     *
     * @return the value of order_pay.pay_status
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public Integer getPay_status() {
        return pay_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_status
     *
     * @param pay_status the value for order_pay.pay_status
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setPay_status(Integer pay_status) {
        this.pay_status = pay_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_msg
     *
     * @return the value of order_pay.pay_msg
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public String getPay_msg() {
        return pay_msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_msg
     *
     * @param pay_msg the value for order_pay.pay_msg
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setPay_msg(String pay_msg) {
        this.pay_msg = pay_msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_time
     *
     * @return the value of order_pay.pay_time
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public Date getPay_time() {
        return pay_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_time
     *
     * @param pay_time the value for order_pay.pay_time
     *
     * @mbggenerated Tue Dec 20 15:18:33 CST 2016
     */
    public void setPay_time(Date pay_time) {
        this.pay_time = pay_time;
    }
}