package cn.bnsr.edu_yun.frontstage.base.po;

public class School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.id
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.vNo
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private Integer vNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private String schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.provinceId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.cityId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.countyId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private String countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolName
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolType
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    private String schoolType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.id
     *
     * @return the value of school.id
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.id
     *
     * @param id the value for school.id
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.vNo
     *
     * @return the value of school.vNo
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public Integer getvNo() {
        return vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.vNo
     *
     * @param vNo the value for school.vNo
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setvNo(Integer vNo) {
        this.vNo = vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolId
     *
     * @return the value of school.schoolId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolId
     *
     * @param schoolId the value for school.schoolId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.provinceId
     *
     * @return the value of school.provinceId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.provinceId
     *
     * @param provinceId the value for school.provinceId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.cityId
     *
     * @return the value of school.cityId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.cityId
     *
     * @param cityId the value for school.cityId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.countyId
     *
     * @return the value of school.countyId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public String getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.countyId
     *
     * @param countyId the value for school.countyId
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setCountyId(String countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolName
     *
     * @return the value of school.schoolName
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolName
     *
     * @param schoolName the value for school.schoolName
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolType
     *
     * @return the value of school.schoolType
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public String getSchoolType() {
        return schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolType
     *
     * @param schoolType the value for school.schoolType
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    public void setSchoolType(String schoolType) {
        this.schoolType = schoolType;
    }
}