package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Long user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.school
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.course
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String course;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.titles
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String titles;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.pubver_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String pubver_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.school_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Long school_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.grade_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer grade_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.true_name
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String true_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.sex
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ID_number
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String ID_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.picture1
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String picture1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.picture2
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String picture2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.picture3
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String picture3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.apply_time
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Date apply_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.review_time
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Date review_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.type
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.certificated
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer certificated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.position_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer position_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.area_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String area_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.titles_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer titles_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.certificate_type
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private Integer certificate_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.profile
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	private String profile;

	private String username;
	
	private int is_recommended;
	
	private String signature;
	
	private String rank;
	
	private String microblog;
	
	private int blog_open;
	
	private String wechat;
	
	private int chat_open;
	
	private String qq;
	
	private int qq_open;
	
	private Integer default_profile;
	
	private Integer default_signature;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.id
	 * @return  the value of user_info.id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.id
	 * @param id  the value for user_info.id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_id
	 * @return  the value of user_info.user_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Long getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_id
	 * @param user_id  the value for user_info.user_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.school
	 * @return  the value of user_info.school
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.school
	 * @param school  the value for user_info.school
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.course
	 * @return  the value of user_info.course
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getCourse() {
		return course;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.course
	 * @param course  the value for user_info.course
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setCourse(String course) {
		this.course = course;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.titles
	 * @return  the value of user_info.titles
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getTitles() {
		return titles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.titles
	 * @param titles  the value for user_info.titles
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setTitles(String titles) {
		this.titles = titles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.pubver_id
	 * @return  the value of user_info.pubver_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getPubver_id() {
		return pubver_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.pubver_id
	 * @param pubver_id  the value for user_info.pubver_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setPubver_id(String pubver_id) {
		this.pubver_id = pubver_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.school_id
	 * @return  the value of user_info.school_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Long getSchool_id() {
		return school_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.school_id
	 * @param school_id  the value for user_info.school_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setSchool_id(Long school_id) {
		this.school_id = school_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.grade_id
	 * @return  the value of user_info.grade_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getGrade_id() {
		return grade_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.grade_id
	 * @param grade_id  the value for user_info.grade_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setGrade_id(Integer grade_id) {
		this.grade_id = grade_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.true_name
	 * @return  the value of user_info.true_name
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getTrue_name() {
		return true_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.true_name
	 * @param true_name  the value for user_info.true_name
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setTrue_name(String true_name) {
		this.true_name = true_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.sex
	 * @return  the value of user_info.sex
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.sex
	 * @param sex  the value for user_info.sex
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ID_number
	 * @return  the value of user_info.ID_number
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getID_number() {
		return ID_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ID_number
	 * @param ID_number  the value for user_info.ID_number
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setID_number(String ID_number) {
		this.ID_number = ID_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.picture1
	 * @return  the value of user_info.picture1
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getPicture1() {
		return picture1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.picture1
	 * @param picture1  the value for user_info.picture1
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setPicture1(String picture1) {
		this.picture1 = picture1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.picture2
	 * @return  the value of user_info.picture2
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getPicture2() {
		return picture2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.picture2
	 * @param picture2  the value for user_info.picture2
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setPicture2(String picture2) {
		this.picture2 = picture2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.picture3
	 * @return  the value of user_info.picture3
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getPicture3() {
		return picture3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.picture3
	 * @param picture3  the value for user_info.picture3
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setPicture3(String picture3) {
		this.picture3 = picture3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.apply_time
	 * @return  the value of user_info.apply_time
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Date getApply_time() {
		return apply_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.apply_time
	 * @param apply_time  the value for user_info.apply_time
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setApply_time(Date apply_time) {
		this.apply_time = apply_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.review_time
	 * @return  the value of user_info.review_time
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Date getReview_time() {
		return review_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.review_time
	 * @param review_time  the value for user_info.review_time
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setReview_time(Date review_time) {
		this.review_time = review_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.type
	 * @return  the value of user_info.type
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.type
	 * @param type  the value for user_info.type
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.certificated
	 * @return  the value of user_info.certificated
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getCertificated() {
		return certificated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.certificated
	 * @param certificated  the value for user_info.certificated
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setCertificated(Integer certificated) {
		this.certificated = certificated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.position_id
	 * @return  the value of user_info.position_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getPosition_id() {
		return position_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.position_id
	 * @param position_id  the value for user_info.position_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setPosition_id(Integer position_id) {
		this.position_id = position_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.area_id
	 * @return  the value of user_info.area_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getArea_id() {
		return area_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.area_id
	 * @param area_id  the value for user_info.area_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setArea_id(String area_id) {
		this.area_id = area_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.titles_id
	 * @return  the value of user_info.titles_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getTitles_id() {
		return titles_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.titles_id
	 * @param titles_id  the value for user_info.titles_id
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setTitles_id(Integer titles_id) {
		this.titles_id = titles_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.certificate_type
	 * @return  the value of user_info.certificate_type
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public Integer getCertificate_type() {
		return certificate_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.certificate_type
	 * @param certificate_type  the value for user_info.certificate_type
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setCertificate_type(Integer certificate_type) {
		this.certificate_type = certificate_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.profile
	 * @return  the value of user_info.profile
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public String getProfile() {
		return profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.profile
	 * @param profile  the value for user_info.profile
	 * @mbggenerated  Fri Dec 16 11:23:37 CST 2016
	 */
	public void setProfile(String profile) {
		this.profile = profile;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getIs_recommended() {
		return is_recommended;
	}

	public void setIs_recommended(int is_recommended) {
		this.is_recommended = is_recommended;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getRank() {
		return rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	public String getMicroblog() {
		return microblog;
	}

	public void setMicroblog(String microblog) {
		this.microblog = microblog;
	}

	public int getBlog_open() {
		return blog_open;
	}

	public void setBlog_open(int blog_open) {
		this.blog_open = blog_open;
	}

	public String getWechat() {
		return wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	public int getChat_open() {
		return chat_open;
	}

	public void setChat_open(int chat_open) {
		this.chat_open = chat_open;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public int getQq_open() {
		return qq_open;
	}

	public void setQq_open(int qq_open) {
		this.qq_open = qq_open;
	}

	public Integer getDefault_profile() {
		return default_profile;
	}

	public void setDefault_profile(Integer default_profile) {
		this.default_profile = default_profile;
	}

	public Integer getDefault_signature() {
		return default_signature;
	}

	public void setDefault_signature(Integer default_signature) {
		this.default_signature = default_signature;
	}
}