package cn.bnsr.edu_yun.frontstage.tiku.po;

public class ExamAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.test_questions_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long test_questions_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.exam_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long exam_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.is_right
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer is_right;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.answer_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Double answer_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.answer_comment
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String answer_comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.answer
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.id
     *
     * @return the value of exam_answer.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.id
     *
     * @param id the value for exam_answer.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.test_questions_id
     *
     * @return the value of exam_answer.test_questions_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getTest_questions_id() {
        return test_questions_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.test_questions_id
     *
     * @param test_questions_id the value for exam_answer.test_questions_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setTest_questions_id(Long test_questions_id) {
        this.test_questions_id = test_questions_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.exam_id
     *
     * @return the value of exam_answer.exam_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getExam_id() {
        return exam_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.exam_id
     *
     * @param exam_id the value for exam_answer.exam_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setExam_id(Long exam_id) {
        this.exam_id = exam_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.is_right
     *
     * @return the value of exam_answer.is_right
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getIs_right() {
        return is_right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.is_right
     *
     * @param is_right the value for exam_answer.is_right
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setIs_right(Integer is_right) {
        this.is_right = is_right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.answer_score
     *
     * @return the value of exam_answer.answer_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Double getAnswer_score() {
        return answer_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.answer_score
     *
     * @param answer_score the value for exam_answer.answer_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setAnswer_score(Double answer_score) {
        this.answer_score = answer_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.answer_comment
     *
     * @return the value of exam_answer.answer_comment
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getAnswer_comment() {
        return answer_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.answer_comment
     *
     * @param answer_comment the value for exam_answer.answer_comment
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setAnswer_comment(String answer_comment) {
        this.answer_comment = answer_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.answer
     *
     * @return the value of exam_answer.answer
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.answer
     *
     * @param answer the value for exam_answer.answer
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }
}