package cn.bnsr.edu_yun.frontstage.train.po;

public class MessageFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_file.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_file.path
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_file.message_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long message_id;

    private String file_name;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_file.id
     *
     * @return the value of message_file.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_file.id
     *
     * @param id the value for message_file.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_file.path
     *
     * @return the value of message_file.path
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_file.path
     *
     * @param path the value for message_file.path
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_file.message_id
     *
     * @return the value of message_file.message_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getMessage_id() {
        return message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_file.message_id
     *
     * @param message_id the value for message_file.message_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setMessage_id(Long message_id) {
        this.message_id = message_id;
    }

	public String getFile_name() {
		return file_name;
	}

	public void setFile_name(String file_name) {
		this.file_name = file_name;
	}
}