package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.train.po.Workshop;
import cn.bnsr.edu_yun.frontstage.train.view.CommunityCenterView;
import cn.bnsr.edu_yun.frontstage.train.view.DataStatsView;
import cn.bnsr.edu_yun.frontstage.train.view.WorkshopView;

public interface WorkshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workshop
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workshop
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int insert(Workshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workshop
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int insertSelective(Workshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workshop
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    Workshop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workshop
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int updateByPrimaryKeySelective(Workshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workshop
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    int updateByPrimaryKey(Workshop record);
    
    List<WorkshopView> showWorkshop(WorkshopView workshopView);
    
    int queryWorkshopCount(WorkshopView workshopView);
    
	List<DataStatsView> workshopDataStats(DataStatsView dataStatsView);
    
    WorkshopView showWorkshopById(Long id);
    
    List<WorkshopView> queryMyWorkshop(WorkshopView workshopView);

    List<Workshop> queryWorkshops();
    
    List<WorkshopView> queryWorkshopCommunity(CommunityCenterView communityCenterView);

    int queryWorkshopCommunityCount(CommunityCenterView communityCenterView);

	int queryMyWorkshopCount(WorkshopView workshopView);
	
	//后台
	List<WorkshopView> search(WorkshopView workshopView);
	
	Long total(WorkshopView workshopView);
	
	/**
	 * 推荐时获取最大推荐序号
	 */
    Long getMaxSeq(Long community_id);
}