package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class Notification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.user_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notice_type_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Integer notice_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notice_time
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Date notice_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.create_time
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.is_read
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Integer is_read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.other_user_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Long other_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.source_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Long source_id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.source_type
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private int source_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.question_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Long question_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.course_hour_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    private Long course_hour_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.user_id
     *
     * @return the value of notification.user_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.user_id
     *
     * @param user_id the value for notification.user_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notice_type_id
     *
     * @return the value of notification.notice_type_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Integer getNotice_type_id() {
        return notice_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notice_type_id
     *
     * @param notice_type_id the value for notification.notice_type_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setNotice_type_id(Integer notice_type_id) {
        this.notice_type_id = notice_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notice_time
     *
     * @return the value of notification.notice_time
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Date getNotice_time() {
        return notice_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notice_time
     *
     * @param notice_time the value for notification.notice_time
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setNotice_time(Date notice_time) {
        this.notice_time = notice_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.create_time
     *
     * @return the value of notification.create_time
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.create_time
     *
     * @param create_time the value for notification.create_time
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.is_read
     *
     * @return the value of notification.is_read
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Integer getIs_read() {
        return is_read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.is_read
     *
     * @param is_read the value for notification.is_read
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setIs_read(Integer is_read) {
        this.is_read = is_read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.other_user_id
     *
     * @return the value of notification.other_user_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Long getOther_user_id() {
        return other_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.other_user_id
     *
     * @param other_user_id the value for notification.other_user_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setOther_user_id(Long other_user_id) {
        this.other_user_id = other_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.source_id
     *
     * @return the value of notification.source_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Long getSource_id() {
        return source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.source_id
     *
     * @param course_id the value for notification.source_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setSource_id(Long source_id) {
        this.source_id = source_id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.source_type
     *
     * @return the value of notification.source_type
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public int getSource_type() {
    	return source_type;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.source_type
     *
     * @param course_id the value for notification.source_type
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setSource_type(int source_type) {
    	this.source_type = source_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.question_id
     *
     * @return the value of notification.question_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Long getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.question_id
     *
     * @param question_id the value for notification.question_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setQuestion_id(Long question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.course_hour_id
     *
     * @return the value of notification.course_hour_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public Long getCourse_hour_id() {
        return course_hour_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.course_hour_id
     *
     * @param course_hour_id the value for notification.course_hour_id
     *
     * @mbggenerated Fri Dec 02 14:29:10 CST 2016
     */
    public void setCourse_hour_id(Long course_hour_id) {
        this.course_hour_id = course_hour_id;
    }
}