package cn.bnsr.edu_yun.frontstage.base.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.backstage.resource.view.FileDetailView;
import cn.bnsr.edu_yun.frontstage.base.po.BookCat;

public interface BookCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_cat
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_cat
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    int insert(BookCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_cat
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    int insertSelective(BookCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_cat
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    BookCat selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_cat
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    int updateByPrimaryKeySelective(BookCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_cat
     *
     * @mbggenerated Thu Sep 01 12:35:03 CST 2016
     */
    int updateByPrimaryKey(BookCat record);

	List<BookCat> queryBookCat(@Param("bookId")String bookId );
    
	BookCat selectBybooId(String bookCatelogId);
	
	/**根据章节id查询所有上级分类*/
	public FileDetailView querAllUpClassify(String parent_id);
	List<BookCat> selectByPid(String parent_id);
}