package cn.bnsr.edu_yun.frontstage.base.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.base.po.School;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    School selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Tue Aug 30 18:25:01 CST 2016
     */
    int updateByPrimaryKey(School record);
    List<School> selectByCountyId(String countyId);//按县区id查询学校
    List<School> selectByProvinceId(String provinceId);
	List<School> selectByCityId(String cityId);
	int selectAll(@Param("schoolName")String schoolName,@Param("provinceId")String provinceId,@Param("cityId")String cityId,@Param("countyId")String countyId);
	List<School> selectByPage(@Param("schoolName")String schoolName,@Param("provinceId")String provinceId,@Param("cityId")String cityId,@Param("countyId")String countyId,@Param("start")long start,@Param("pageSize")long pageSize);
}