package cn.bnsr.edu_yun.frontstage.base.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.base.po.SubjectList;

public interface SubjectListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_list
     *
     * @mbggenerated Thu Sep 01 10:07:41 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_list
     *
     * @mbggenerated Thu Sep 01 10:07:41 CST 2016
     */
    int insert(SubjectList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_list
     *
     * @mbggenerated Thu Sep 01 10:07:41 CST 2016
     */
    int insertSelective(SubjectList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_list
     *
     * @mbggenerated Thu Sep 01 10:07:41 CST 2016
     */
    SubjectList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_list
     *
     * @mbggenerated Thu Sep 01 10:07:41 CST 2016
     */
    int updateByPrimaryKeySelective(SubjectList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_list
     *
     * @mbggenerated Thu Sep 01 10:07:41 CST 2016
     */
    int updateByPrimaryKey(SubjectList record);
    List<SubjectList> selectAll();

	List<SubjectList> querySubject(String subId);
	SubjectList selectBySubjectListId(String subjectId);
	List<SubjectList> selectByPid(String parent_id);
	List<SubjectList> selectOtherSubject(String parent_id);

	List<SubjectList> searchSubject(@Param("list") List<String> list);
}