package cn.bnsr.edu_yun.frontstage.base.mapper;

import cn.bnsr.edu_yun.frontstage.base.po.UploadFile;

public interface UploadFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    long insert(UploadFile uploadFile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    long insertSelective(UploadFile uploadFile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    UploadFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    long updateByPrimaryKeySelective(UploadFile uploadFile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbggenerated Tue Nov 22 16:14:03 CST 2016
     */
    long updateByPrimaryKey(UploadFile uploadFile);
    
    
}