package cn.bnsr.edu_yun.frontstage.train.po;

import java.util.Date;

public class Train {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.classify_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long classify_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.img
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */

    private Double price;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.old_price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Double old_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.user_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.create_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.recommend_seq
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer recommend_seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.recommend_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Date recommend_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.is_recommend
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer is_recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.status
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.is_sort
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private Integer is_sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.sponsor
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String sponsor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.profile
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    private String profile;
    
    private int type;
    
	private int is_check;
	
	private Integer is_default_img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.id
     *
     * @return the value of train.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.id
     *
     * @param id the value for train.id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.name
     *
     * @return the value of train.name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.name
     *
     * @param name the value for train.name
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.classify_id
     *
     * @return the value of train.classify_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getClassify_id() {
        return classify_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.classify_id
     *
     * @param classify_id the value for train.classify_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setClassify_id(Long classify_id) {
        this.classify_id = classify_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.img
     *
     * @return the value of train.img
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.img
     *
     * @param img the value for train.img
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.price
     *
     * @return the value of train.price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.price
     *
     * @param price the value for train.price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.old_price
     *
     * @return the value of train.old_price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Double getOld_price() {
        return old_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.old_price
     *
     * @param old_price the value for train.old_price
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setOld_price(Double old_price) {
        this.old_price = old_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.user_id
     *
     * @return the value of train.user_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.user_id
     *
     * @param user_id the value for train.user_id
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.create_time
     *
     * @return the value of train.create_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.create_time
     *
     * @param create_time the value for train.create_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.recommend_seq
     *
     * @return the value of train.recommend_seq
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getRecommend_seq() {
        return recommend_seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.recommend_seq
     *
     * @param recommend_seq the value for train.recommend_seq
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setRecommend_seq(Integer recommend_seq) {
        this.recommend_seq = recommend_seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.recommend_time
     *
     * @return the value of train.recommend_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Date getRecommend_time() {
        return recommend_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.recommend_time
     *
     * @param recommend_time the value for train.recommend_time
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setRecommend_time(Date recommend_time) {
        this.recommend_time = recommend_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.is_recommend
     *
     * @return the value of train.is_recommend
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getIs_recommend() {
        return is_recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.is_recommend
     *
     * @param is_recommend the value for train.is_recommend
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setIs_recommend(Integer is_recommend) {
        this.is_recommend = is_recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.status
     *
     * @return the value of train.status
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.status
     *
     * @param status the value for train.status
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.is_sort
     *
     * @return the value of train.is_sort
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public Integer getIs_sort() {
        return is_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.is_sort
     *
     * @param is_sort the value for train.is_sort
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setIs_sort(Integer is_sort) {
        this.is_sort = is_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.sponsor
     *
     * @return the value of train.sponsor
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getSponsor() {
        return sponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.sponsor
     *
     * @param sponsor the value for train.sponsor
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setSponsor(String sponsor) {
        this.sponsor = sponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.profile
     *
     * @return the value of train.profile
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.profile
     *
     * @param profile the value for train.profile
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getIs_check() {
		return is_check;
	}

	public void setIs_check(int is_check) {
		this.is_check = is_check;
	}

	public Integer getIs_default_img() {
		return is_default_img;
	}

	public void setIs_default_img(Integer is_default_img) {
		this.is_default_img = is_default_img;
	}
    
}