package cn.bnsr.edu_yun.frontstage.base.mapper;

import cn.bnsr.edu_yun.frontstage.base.po.UserAppraiseReason;

public interface UserAppraiseReasonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_appraise_reason
	 * @mbggenerated  Mon Sep 25 14:53:57 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_appraise_reason
	 * @mbggenerated  Mon Sep 25 14:53:57 CST 2017
	 */
	int insert(UserAppraiseReason record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_appraise_reason
	 * @mbggenerated  Mon Sep 25 14:53:57 CST 2017
	 */
	int insertSelective(UserAppraiseReason record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_appraise_reason
	 * @mbggenerated  Mon Sep 25 14:53:57 CST 2017
	 */
	UserAppraiseReason selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_appraise_reason
	 * @mbggenerated  Mon Sep 25 14:53:57 CST 2017
	 */
	int updateByPrimaryKeySelective(UserAppraiseReason record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_appraise_reason
	 * @mbggenerated  Mon Sep 25 14:53:57 CST 2017
	 */
	int updateByPrimaryKey(UserAppraiseReason record);
}