package cn.bnsr.edu_yun.frontstage.app.po;

import java.util.Date;

public class AppVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_name
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private String version_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_time
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private Date version_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.major
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private Integer major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.minor
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private Integer minor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.maintenance
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private Integer maintenance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.describe
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_name
     *
     * @return the value of app_version.version_name
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public String getVersion_name() {
        return version_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_name
     *
     * @param version_name the value for app_version.version_name
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setVersion_name(String version_name) {
        this.version_name = version_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_time
     *
     * @return the value of app_version.version_time
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public Date getVersion_time() {
        return version_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_time
     *
     * @param version_time the value for app_version.version_time
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setVersion_time(Date version_time) {
        this.version_time = version_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.major
     *
     * @return the value of app_version.major
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public Integer getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.major
     *
     * @param major the value for app_version.major
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setMajor(Integer major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.minor
     *
     * @return the value of app_version.minor
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public Integer getMinor() {
        return minor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.minor
     *
     * @param minor the value for app_version.minor
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setMinor(Integer minor) {
        this.minor = minor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.maintenance
     *
     * @return the value of app_version.maintenance
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public Integer getMaintenance() {
        return maintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.maintenance
     *
     * @param maintenance the value for app_version.maintenance
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setMaintenance(Integer maintenance) {
        this.maintenance = maintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.describe
     *
     * @return the value of app_version.describe
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.describe
     *
     * @param describe the value for app_version.describe
     *
     * @mbggenerated Thu Dec 28 11:23:35 CST 2017
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }
}