package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.train.po.CourseExamStandard;
import cn.bnsr.edu_yun.frontstage.train.view.CourseExamStandardView;

public interface CourseExamStandardMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course_exam_standard
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course_exam_standard
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	int insert(CourseExamStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course_exam_standard
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	int insertSelective(CourseExamStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course_exam_standard
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	CourseExamStandard selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course_exam_standard
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	int updateByPrimaryKeySelective(CourseExamStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course_exam_standard
	 * @mbggenerated  Tue Dec 20 15:07:28 CST 2016
	 */
	int updateByPrimaryKey(CourseExamStandard record);
	
	List<CourseExamStandardView> queryStandard(CourseExamStandardView examStandardView);

	void deleteExamStandard(@Param("course_hour_id")Long course_hour_id);
	
	Integer queryTotalRatioByCouId(@Param("course_id")Long course_id);
}