package cn.bnsr.edu_yun.frontstage.train.mapper;

import cn.bnsr.edu_yun.frontstage.train.po.TrainItem;

public interface TrainItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int insert(TrainItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int insertSelective(TrainItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    TrainItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int updateByPrimaryKeySelective(TrainItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TrainItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_item
     *
     * @mbggenerated Tue Dec 20 15:07:28 CST 2016
     */
    int updateByPrimaryKey(TrainItem record);
}