package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.train.po.UserDiscuss;
import cn.bnsr.edu_yun.frontstage.train.view.ClassView;
import cn.bnsr.edu_yun.frontstage.train.view.UserDiscussView;


public interface UserDiscussMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	int insert(UserDiscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	int insertSelective(UserDiscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	UserDiscuss selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	int updateByPrimaryKeySelective(UserDiscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(UserDiscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_discuss
	 * @mbggenerated  Fri Mar 03 13:54:44 CST 2017
	 */
	int updateByPrimaryKey(UserDiscuss record);

	List<UserDiscussView> queryDiscuss(UserDiscussView userDiscussView);

	
	/**统计班级的学生发言数*/
	int countClassHomeDiscuss(ClassView record);
	
	List<UserDiscussView> queryClassDiscuss(UserDiscussView userDiscussView);
	
	int countClassDiscuss(UserDiscussView userDiscussView);
	
	int countUserDiscuss(UserDiscuss userDiscuss);
	
	

}