package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.train.po.UserCollect;
import cn.bnsr.edu_yun.frontstage.train.view.UserCollectView;

public interface UserCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Thu Feb 23 14:58:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Thu Feb 23 14:58:58 CST 2017
     */
    int insert(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Thu Feb 23 14:58:58 CST 2017
     */
    int insertSelective(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Thu Feb 23 14:58:58 CST 2017
     */
    UserCollect selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Thu Feb 23 14:58:58 CST 2017
     */
    int updateByPrimaryKeySelective(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Thu Feb 23 14:58:58 CST 2017
     */
    int updateByPrimaryKey(UserCollect record);
    
    UserCollect selectByCourseIdAndUserId(UserCollect userCollect);

    List<UserCollectView> queryMyCollect(UserCollectView userCollectView);
	
    int countMyCollect(UserCollectView userCollectView);
    
    int countMyAllCollect(Long user_id);
}