package cn.bnsr.edu_yun.backstage.base.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.backstage.base.po.Role;
import cn.bnsr.edu_yun.backstage.base.view.RoleView;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbggenerated  Tue Aug 30 09:06:16 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbggenerated  Tue Aug 30 09:06:16 CST 2016
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbggenerated  Tue Aug 30 09:06:16 CST 2016
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbggenerated  Tue Aug 30 09:06:16 CST 2016
	 */
	Role selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbggenerated  Tue Aug 30 09:06:16 CST 2016
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbggenerated  Tue Aug 30 09:06:16 CST 2016
	 */
	int updateByPrimaryKey(Role record);

	public List<Role> find(RoleView roleView);

	public Long count(RoleView roleView);

	public List<Role> selectAll(@Param("level")String level);
	
	String queryBackUserLevel(Long id);
}