package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class OnlineNum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_num.id
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_num.online_num
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    private Long online_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_num.create_time
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_num.id
     *
     * @return the value of online_num.id
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_num.id
     *
     * @param id the value for online_num.id
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_num.online_num
     *
     * @return the value of online_num.online_num
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    public Long getOnline_num() {
        return online_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_num.online_num
     *
     * @param online_num the value for online_num.online_num
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    public void setOnline_num(Long online_num) {
        this.online_num = online_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_num.create_time
     *
     * @return the value of online_num.create_time
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_num.create_time
     *
     * @param create_time the value for online_num.create_time
     *
     * @mbggenerated Fri Oct 20 15:53:17 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}