package cn.bnsr.edu_yun.frontstage.resource.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.resource.po.File_property;
import cn.bnsr.edu_yun.frontstage.resource.view.FileView;

public interface File_propertyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_property
	 * @mbggenerated  Fri Aug 05 10:31:12 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_property
	 * @mbggenerated  Fri Aug 05 10:31:12 CST 2016
	 */
	int insert(File_property record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_property
	 * @mbggenerated  Fri Aug 05 10:31:12 CST 2016
	 */
	int insertSelective(File_property record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_property
	 * @mbggenerated  Fri Aug 05 10:31:12 CST 2016
	 */
	File_property selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_property
	 * @mbggenerated  Fri Aug 05 10:31:12 CST 2016
	 */
	int updateByPrimaryKeySelective(File_property record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_property
	 * @mbggenerated  Fri Aug 05 10:31:12 CST 2016
	 */
	int updateByPrimaryKey(File_property record);

	public FileView queryCount(List<String> proIds);

	public String querScoreNum(@Param("userId")Long userId, @Param("type")String type);
}