package cn.bnsr.edu_yun.frontstage.resource.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.resource.po.File_label;

public interface File_labelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_label
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_label
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insert(File_label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_label
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int insertSelective(File_label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_label
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    File_label selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_label
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKeySelective(File_label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_label
     *
     * @mbggenerated Tue Jul 26 16:00:41 CST 2016
     */
    int updateByPrimaryKey(File_label record);

    /**根据文档id查询标签id*/
    List<String> getByFileId(String id);
}