package cn.bnsr.edu_yun.frontstage.resource.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.resource.po.File_type;

public interface File_typeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbggenerated  Thu Aug 11 16:56:45 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbggenerated  Thu Aug 11 16:56:45 CST 2016
	 */
	int insert(File_type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbggenerated  Thu Aug 11 16:56:45 CST 2016
	 */
	int insertSelective(File_type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbggenerated  Thu Aug 11 16:56:45 CST 2016
	 */
	File_type selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbggenerated  Thu Aug 11 16:56:45 CST 2016
	 */
	int updateByPrimaryKeySelective(File_type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbggenerated  Thu Aug 11 16:56:45 CST 2016
	 */
	int updateByPrimaryKey(File_type record);

	List<File_type> findAllFileType();
}