package cn.bnsr.edu_yun.frontstage.train.po;

public class MessageRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_relation.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_relation.message_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long message_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_relation.source_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Long source_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_relation.source_type
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    private Integer source_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_relation.id
     *
     * @return the value of message_relation.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_relation.id
     *
     * @param id the value for message_relation.id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_relation.message_id
     *
     * @return the value of message_relation.message_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getMessage_id() {
        return message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_relation.message_id
     *
     * @param message_id the value for message_relation.message_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setMessage_id(Long message_id) {
        this.message_id = message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_relation.source_id
     *
     * @return the value of message_relation.source_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Long getSource_id() {
        return source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_relation.source_id
     *
     * @param source_id the value for message_relation.source_id
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setSource_id(Long source_id) {
        this.source_id = source_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_relation.source_type
     *
     * @return the value of message_relation.source_type
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public Integer getSource_type() {
        return source_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_relation.source_type
     *
     * @param source_type the value for message_relation.source_type
     *
     * @mbggenerated Fri May 12 15:21:17 CST 2017
     */
    public void setSource_type(Integer source_type) {
        this.source_type = source_type;
    }
}