package cn.bnsr.edu_yun.frontstage.base.mapper;

import cn.bnsr.edu_yun.backstage.base.view.DefaultUserSetView;
import cn.bnsr.edu_yun.frontstage.base.po.DefaultVarchar;

public interface DefaultVarcharMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_varchar
	 * @mbggenerated  Thu Sep 14 16:32:49 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_varchar
	 * @mbggenerated  Thu Sep 14 16:32:49 CST 2017
	 */
	int insert(DefaultVarchar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_varchar
	 * @mbggenerated  Thu Sep 14 16:32:49 CST 2017
	 */
	int insertSelective(DefaultVarchar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_varchar
	 * @mbggenerated  Thu Sep 14 16:32:49 CST 2017
	 */
	DefaultVarchar selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_varchar
	 * @mbggenerated  Thu Sep 14 16:32:49 CST 2017
	 */
	int updateByPrimaryKeySelective(DefaultVarchar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_varchar
	 * @mbggenerated  Thu Sep 14 16:32:49 CST 2017
	 */
	int updateByPrimaryKey(DefaultVarchar record);
	
	DefaultUserSetView queryOne(DefaultUserSetView record);
	
}