package cn.bnsr.edu_yun.frontstage.tiku.po;

import java.util.Date;

public class Exam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.test_paper_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long test_paper_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.status
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_hour
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String exam_hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Double exam_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer exam_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.marking_user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long marking_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.marking_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Date marking_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.grade
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_comment
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String exam_comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.submit_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Date submit_time;

    private Long class_id;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.id
     *
     * @return the value of exam.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.id
     *
     * @param id the value for exam.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.user_id
     *
     * @return the value of exam.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.user_id
     *
     * @param user_id the value for exam.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.test_paper_id
     *
     * @return the value of exam.test_paper_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getTest_paper_id() {
        return test_paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.test_paper_id
     *
     * @param test_paper_id the value for exam.test_paper_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setTest_paper_id(Long test_paper_id) {
        this.test_paper_id = test_paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.status
     *
     * @return the value of exam.status
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.status
     *
     * @param status the value for exam.status
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_hour
     *
     * @return the value of exam.exam_hour
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getExam_hour() {
        return exam_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_hour
     *
     * @param exam_hour the value for exam.exam_hour
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setExam_hour(String exam_hour) {
        this.exam_hour = exam_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_score
     *
     * @return the value of exam.exam_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Double getExam_score() {
        return exam_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_score
     *
     * @param exam_score the value for exam.exam_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setExam_score(Double exam_score) {
        this.exam_score = exam_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_type
     *
     * @return the value of exam.exam_type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getExam_type() {
        return exam_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_type
     *
     * @param exam_type the value for exam.exam_type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setExam_type(Integer exam_type) {
        this.exam_type = exam_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.marking_user_id
     *
     * @return the value of exam.marking_user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getMarking_user_id() {
        return marking_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.marking_user_id
     *
     * @param marking_user_id the value for exam.marking_user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setMarking_user_id(Long marking_user_id) {
        this.marking_user_id = marking_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.marking_time
     *
     * @return the value of exam.marking_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Date getMarking_time() {
        return marking_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.marking_time
     *
     * @param marking_time the value for exam.marking_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setMarking_time(Date marking_time) {
        this.marking_time = marking_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.grade
     *
     * @return the value of exam.grade
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.grade
     *
     * @param grade the value for exam.grade
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_comment
     *
     * @return the value of exam.exam_comment
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getExam_comment() {
        return exam_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_comment
     *
     * @param exam_comment the value for exam.exam_comment
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setExam_comment(String exam_comment) {
        this.exam_comment = exam_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.submit_time
     *
     * @return the value of exam.submit_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Date getSubmit_time() {
        return submit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.submit_time
     *
     * @param submit_time the value for exam.submit_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setSubmit_time(Date submit_time) {
        this.submit_time = submit_time;
    }

	public Long getClass_id() {
		return class_id;
	}

	public void setClass_id(Long class_id) {
		this.class_id = class_id;
	}
}