package cn.bnsr.edu_yun.frontstage.tiku.po;

public class QuestionMaterial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_material.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_material.question_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long question_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_material.son_question_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long son_question_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_material.id
     *
     * @return the value of question_material.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_material.id
     *
     * @param id the value for question_material.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_material.question_id
     *
     * @return the value of question_material.question_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getQuestion_id() {
        return question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_material.question_id
     *
     * @param question_id the value for question_material.question_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setQuestion_id(Long question_id) {
        this.question_id = question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_material.son_question_id
     *
     * @return the value of question_material.son_question_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getSon_question_id() {
        return son_question_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_material.son_question_id
     *
     * @param son_question_id the value for question_material.son_question_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setSon_question_id(Long son_question_id) {
        this.son_question_id = son_question_id;
    }
}