package cn.bnsr.edu_yun.frontstage.tiku.po;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.difficulty
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer difficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.belong_to
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long belong_to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.belong_type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer belong_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.classify_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long classify_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.update_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.is_son
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer is_son;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.is_item
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer is_item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.right_key
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String right_key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.stem
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String stem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.analysis
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_a
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String option_a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_b
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String option_b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_c
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String option_c;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_d
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String option_d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.option_e
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String option_e;

    private Long course_id;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.difficulty
     *
     * @return the value of question.difficulty
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.difficulty
     *
     * @param difficulty the value for question.difficulty
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.belong_to
     *
     * @return the value of question.belong_to
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getBelong_to() {
        return belong_to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.belong_to
     *
     * @param belong_to the value for question.belong_to
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setBelong_to(Long belong_to) {
        this.belong_to = belong_to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.belong_type
     *
     * @return the value of question.belong_type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getBelong_type() {
        return belong_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.belong_type
     *
     * @param belong_type the value for question.belong_type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setBelong_type(Integer belong_type) {
        this.belong_type = belong_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.classify_id
     *
     * @return the value of question.classify_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getClassify_id() {
        return classify_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.classify_id
     *
     * @param classify_id the value for question.classify_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setClassify_id(Long classify_id) {
        this.classify_id = classify_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.user_id
     *
     * @return the value of question.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.user_id
     *
     * @param user_id the value for question.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.update_time
     *
     * @return the value of question.update_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.update_time
     *
     * @param update_time the value for question.update_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_time
     *
     * @return the value of question.create_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_time
     *
     * @param create_time the value for question.create_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.is_son
     *
     * @return the value of question.is_son
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getIs_son() {
        return is_son;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.is_son
     *
     * @param is_son the value for question.is_son
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setIs_son(Integer is_son) {
        this.is_son = is_son;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type
     *
     * @return the value of question.type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type
     *
     * @param type the value for question.type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.score
     *
     * @return the value of question.score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.score
     *
     * @param score the value for question.score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.is_item
     *
     * @return the value of question.is_item
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getIs_item() {
        return is_item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.is_item
     *
     * @param is_item the value for question.is_item
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setIs_item(Integer is_item) {
        this.is_item = is_item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.right_key
     *
     * @return the value of question.right_key
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getRight_key() {
        return right_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.right_key
     *
     * @param right_key the value for question.right_key
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setRight_key(String right_key) {
        this.right_key = right_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.stem
     *
     * @return the value of question.stem
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getStem() {
        return stem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.stem
     *
     * @param stem the value for question.stem
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setStem(String stem) {
        this.stem = stem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.analysis
     *
     * @return the value of question.analysis
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.analysis
     *
     * @param analysis the value for question.analysis
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_a
     *
     * @return the value of question.option_a
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getOption_a() {
        return option_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_a
     *
     * @param option_a the value for question.option_a
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setOption_a(String option_a) {
        this.option_a = option_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_b
     *
     * @return the value of question.option_b
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getOption_b() {
        return option_b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_b
     *
     * @param option_b the value for question.option_b
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setOption_b(String option_b) {
        this.option_b = option_b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_c
     *
     * @return the value of question.option_c
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getOption_c() {
        return option_c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_c
     *
     * @param option_c the value for question.option_c
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setOption_c(String option_c) {
        this.option_c = option_c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_d
     *
     * @return the value of question.option_d
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getOption_d() {
        return option_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_d
     *
     * @param option_d the value for question.option_d
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setOption_d(String option_d) {
        this.option_d = option_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.option_e
     *
     * @return the value of question.option_e
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getOption_e() {
        return option_e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.option_e
     *
     * @param option_e the value for question.option_e
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setOption_e(String option_e) {
        this.option_e = option_e;
    }

	public Long getCourse_id() {
		return course_id;
	}

	public void setCourse_id(Long course_id) {
		this.course_id = course_id;
	}
}