package cn.bnsr.edu_yun.frontstage.tiku.po;

import java.util.Date;

public class TestPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.name
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.course_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long course_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.timeless
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer timeless;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.mode
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.course_hour_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long course_hour_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.test_difficulty
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String test_difficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.update_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.create_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.total_number
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer total_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.total_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Double total_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.accord_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String accord_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.is_objective
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer is_objective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.status
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.hour_subject_range
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String hour_range;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.subject_range
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private Integer subject_range;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.remarks
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.id
     *
     * @return the value of test_paper.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.id
     *
     * @param id the value for test_paper.id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.name
     *
     * @return the value of test_paper.name
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.name
     *
     * @param name the value for test_paper.name
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.course_id
     *
     * @return the value of test_paper.course_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getCourse_id() {
        return course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.course_id
     *
     * @param course_id the value for test_paper.course_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setCourse_id(Long course_id) {
        this.course_id = course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.timeless
     *
     * @return the value of test_paper.timeless
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getTimeless() {
        return timeless;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.timeless
     *
     * @param timeless the value for test_paper.timeless
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setTimeless(Integer timeless) {
        this.timeless = timeless;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.mode
     *
     * @return the value of test_paper.mode
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.mode
     *
     * @param mode the value for test_paper.mode
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.type
     *
     * @return the value of test_paper.type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.type
     *
     * @param type the value for test_paper.type
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.course_hour_id
     *
     * @return the value of test_paper.course_hour_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getCourse_hour_id() {
        return course_hour_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.course_hour_id
     *
     * @param course_hour_id the value for test_paper.course_hour_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setCourse_hour_id(Long course_hour_id) {
        this.course_hour_id = course_hour_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.test_difficulty
     *
     * @return the value of test_paper.test_difficulty
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getTest_difficulty() {
        return test_difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.test_difficulty
     *
     * @param test_difficulty the value for test_paper.test_difficulty
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setTest_difficulty(String test_difficulty) {
        this.test_difficulty = test_difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.user_id
     *
     * @return the value of test_paper.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.user_id
     *
     * @param user_id the value for test_paper.user_id
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.update_time
     *
     * @return the value of test_paper.update_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.update_time
     *
     * @param update_time the value for test_paper.update_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.create_time
     *
     * @return the value of test_paper.create_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.create_time
     *
     * @param create_time the value for test_paper.create_time
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.total_number
     *
     * @return the value of test_paper.total_number
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getTotal_number() {
        return total_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.total_number
     *
     * @param total_number the value for test_paper.total_number
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setTotal_number(Integer total_number) {
        this.total_number = total_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.total_score
     *
     * @return the value of test_paper.total_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Double getTotal_score() {
        return total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.total_score
     *
     * @param total_score the value for test_paper.total_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setTotal_score(Double total_score) {
        this.total_score = total_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.accord_score
     *
     * @return the value of test_paper.accord_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public String getAccord_score() {
        return accord_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.accord_score
     *
     * @param accord_score the value for test_paper.accord_score
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setAccord_score(String accord_score) {
        this.accord_score = accord_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.is_objective
     *
     * @return the value of test_paper.is_objective
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getIs_objective() {
        return is_objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.is_objective
     *
     * @param is_objective the value for test_paper.is_objective
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setIs_objective(Integer is_objective) {
        this.is_objective = is_objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.status
     *
     * @return the value of test_paper.status
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.status
     *
     * @param status the value for test_paper.status
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.hour_subject_range
     *
     * @return the value of test_paper.hour_subject_range
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */

    public String getHour_range() {
  		return hour_range;
  	}
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.hour_subject_range
     *
     * @param hour_subject_range the value for test_paper.hour_subject_range
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
  	public void setHour_range(String hour_range) {
  		this.hour_range = hour_range;
  	}
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.subject_range
     *
     * @return the value of test_paper.subject_range
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    
    public Integer getSubject_range() {
		return subject_range;
	}
    

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.subject_range
     *
     * @param subject_range the value for test_paper.subject_range
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
	public void setSubject_range(Integer subject_range) {
		this.subject_range = subject_range;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.remarks
     *
     * @return the value of test_paper.remarks
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
	public String getRemarks() {
		return remarks;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.remarks
     *
     * @param remarks the value for test_paper.remarks
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}