package cn.bnsr.edu_yun.frontstage.tiku.po;

public class TestPaperFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper_file.id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper_file.test_paper_id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    private Long test_paper_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper_file.course_file_id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    private Long course_file_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper_file.id
     *
     * @return the value of test_paper_file.id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper_file.id
     *
     * @param id the value for test_paper_file.id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper_file.test_paper_id
     *
     * @return the value of test_paper_file.test_paper_id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    public Long getTest_paper_id() {
        return test_paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper_file.test_paper_id
     *
     * @param test_paper_id the value for test_paper_file.test_paper_id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    public void setTest_paper_id(Long test_paper_id) {
        this.test_paper_id = test_paper_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper_file.course_file_id
     *
     * @return the value of test_paper_file.course_file_id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    public Long getCourse_file_id() {
        return course_file_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper_file.course_file_id
     *
     * @param course_file_id the value for test_paper_file.course_file_id
     *
     * @mbggenerated Tue Dec 20 15:09:35 CST 2016
     */
    public void setCourse_file_id(Long course_file_id) {
        this.course_file_id = course_file_id;
    }
}