package cn.bnsr.edu_yun.frontstage.tiku.po;

public class UserHomeworkScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_homework_score.id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_homework_score.user_id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_homework_score.exam_id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    private Long exam_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_homework_score.score
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_homework_score.status
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_homework_score.id
     *
     * @return the value of user_homework_score.id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_homework_score.id
     *
     * @param id the value for user_homework_score.id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_homework_score.user_id
     *
     * @return the value of user_homework_score.user_id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_homework_score.user_id
     *
     * @param user_id the value for user_homework_score.user_id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_homework_score.exam_id
     *
     * @return the value of user_homework_score.exam_id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public Long getExam_id() {
        return exam_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_homework_score.exam_id
     *
     * @param exam_id the value for user_homework_score.exam_id
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public void setExam_id(Long exam_id) {
        this.exam_id = exam_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_homework_score.score
     *
     * @return the value of user_homework_score.score
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_homework_score.score
     *
     * @param score the value for user_homework_score.score
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_homework_score.status
     *
     * @return the value of user_homework_score.status
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_homework_score.status
     *
     * @param status the value for user_homework_score.status
     *
     * @mbggenerated Thu May 11 12:49:25 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}