package cn.bnsr.edu_yun.frontstage.tiku.mapper;

import java.util.List;

import cn.bnsr.edu_yun.frontstage.tiku.po.Exam;
import cn.bnsr.edu_yun.frontstage.tiku.view.ExamView;

public interface ExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int insert(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int insertSelective(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    Exam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int updateByPrimaryKeySelective(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Tue Dec 06 10:04:22 CST 2016
     */
    int updateByPrimaryKey(Exam record);
    /**
     * 查试卷的状态，是否交卷
     * @param record
     * @return
     */
    Exam selectStatus(Exam record);
    //试卷列表
    List<ExamView> queryExam(ExamView examView);
    //总数
    int queryExamCount(ExamView examView);
    //我的试卷列表
    List<ExamView> queryMyExam(ExamView examView);
    //我的试卷总数
    int queryMyExamCount(ExamView examView);
    
    Integer queryExamGrade(ExamView examView);
    //当前社区下班级作业/考试
    List<ExamView> queryMyCommunityExam(ExamView examView);
    
    int queryMyCommunityExamCount(ExamView examView);
}