package cn.bnsr.edu_yun.frontstage.train.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bnsr.edu_yun.frontstage.train.po.ClassifyRelation;
import cn.bnsr.edu_yun.frontstage.train.view.ClassifyRelationView;

public interface ClassifyRelationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classify_relation
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classify_relation
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	int insert(ClassifyRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classify_relation
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	int insertSelective(ClassifyRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classify_relation
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	ClassifyRelation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classify_relation
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	int updateByPrimaryKeySelective(ClassifyRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classify_relation
	 * @mbggenerated  Thu May 18 15:47:28 CST 2017
	 */
	int updateByPrimaryKey(ClassifyRelation record);

	List<ClassifyRelationView> queryAllBaseClassify(ClassifyRelationView classify);
    
    List<ClassifyRelation> getSonClassifys(@Param("parent_id")Long parent_id);
    
    List<ClassifyRelation> queryCLassifysByPid(@Param("parent_id")Long parentId,@Param("source_type")Integer sourceType,
			@Param("type")Integer type);
    
    int countBaseClassifyRelation(ClassifyRelationView classify);
    
    Integer getMaxSeq(ClassifyRelationView classify);
}