package cn.bnsr.edu_yun.frontstage.base.po;

import java.util.Date;

public class IpIntercept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.id
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.remote_ip
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String remote_ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.country
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.area
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.region
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.create_time
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private Date create_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.city
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.county
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String county;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.isp
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String isp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.is_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private Integer is_intercept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ip_intercept.province_id
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	private String province_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.id
	 * @return  the value of ip_intercept.id
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.id
	 * @param id  the value for ip_intercept.id
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.remote_ip
	 * @return  the value of ip_intercept.remote_ip
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getRemote_ip() {
		return remote_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.remote_ip
	 * @param remote_ip  the value for ip_intercept.remote_ip
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setRemote_ip(String remote_ip) {
		this.remote_ip = remote_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.country
	 * @return  the value of ip_intercept.country
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.country
	 * @param country  the value for ip_intercept.country
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.area
	 * @return  the value of ip_intercept.area
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.area
	 * @param area  the value for ip_intercept.area
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.region
	 * @return  the value of ip_intercept.region
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.region
	 * @param region  the value for ip_intercept.region
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.create_time
	 * @return  the value of ip_intercept.create_time
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.create_time
	 * @param create_time  the value for ip_intercept.create_time
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.city
	 * @return  the value of ip_intercept.city
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.city
	 * @param city  the value for ip_intercept.city
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.county
	 * @return  the value of ip_intercept.county
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.county
	 * @param county  the value for ip_intercept.county
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setCounty(String county) {
		this.county = county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.isp
	 * @return  the value of ip_intercept.isp
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getIsp() {
		return isp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.isp
	 * @param isp  the value for ip_intercept.isp
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setIsp(String isp) {
		this.isp = isp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.is_intercept
	 * @return  the value of ip_intercept.is_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public Integer getIs_intercept() {
		return is_intercept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.is_intercept
	 * @param is_intercept  the value for ip_intercept.is_intercept
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setIs_intercept(Integer is_intercept) {
		this.is_intercept = is_intercept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ip_intercept.province_id
	 * @return  the value of ip_intercept.province_id
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public String getProvince_id() {
		return province_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ip_intercept.province_id
	 * @param province_id  the value for ip_intercept.province_id
	 * @mbggenerated  Wed Oct 11 14:10:47 CST 2017
	 */
	public void setProvince_id(String province_id) {
		this.province_id = province_id;
	}
}