package cn.bnsr.edu_yun.frontstage.xbjy.po;

import java.util.Date;

public class LessonAssess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_assess.id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_assess.lesson_id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    private Long lesson_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_assess.user_id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_assess.update_time
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_assess.excellent
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    private Integer excellent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_assess.opinion
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    private String opinion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_assess.id
     *
     * @return the value of lesson_assess.id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_assess.id
     *
     * @param id the value for lesson_assess.id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_assess.lesson_id
     *
     * @return the value of lesson_assess.lesson_id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public Long getLesson_id() {
        return lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_assess.lesson_id
     *
     * @param lesson_id the value for lesson_assess.lesson_id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public void setLesson_id(Long lesson_id) {
        this.lesson_id = lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_assess.user_id
     *
     * @return the value of lesson_assess.user_id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_assess.user_id
     *
     * @param user_id the value for lesson_assess.user_id
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_assess.update_time
     *
     * @return the value of lesson_assess.update_time
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_assess.update_time
     *
     * @param update_time the value for lesson_assess.update_time
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_assess.excellent
     *
     * @return the value of lesson_assess.excellent
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public Integer getExcellent() {
        return excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_assess.excellent
     *
     * @param excellent the value for lesson_assess.excellent
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public void setExcellent(Integer excellent) {
        this.excellent = excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_assess.opinion
     *
     * @return the value of lesson_assess.opinion
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_assess.opinion
     *
     * @param opinion the value for lesson_assess.opinion
     *
     * @mbggenerated Wed Apr 05 14:03:54 CST 2017
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }
}