package cn.bnsr.edu_yun.frontstage.xbjy.po;

import java.util.Date;

public class LessonDesign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.lesson_id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private Long lesson_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.create_time
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.user_id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.version_num
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private Integer version_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.status
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.edu_goal
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String edu_goal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.lesson_divide
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String lesson_divide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.materials_analysis
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String materials_analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.student_analysis
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String student_analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.strategy_design
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String strategy_design;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.focus_difficulty
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String focus_difficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.media_selection
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String media_selection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.teaching_process
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String teaching_process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_design.typography_design
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    private String typography_design;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.id
     *
     * @return the value of lesson_design.id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.id
     *
     * @param id the value for lesson_design.id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.lesson_id
     *
     * @return the value of lesson_design.lesson_id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public Long getLesson_id() {
        return lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.lesson_id
     *
     * @param lesson_id the value for lesson_design.lesson_id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setLesson_id(Long lesson_id) {
        this.lesson_id = lesson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.create_time
     *
     * @return the value of lesson_design.create_time
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.create_time
     *
     * @param create_time the value for lesson_design.create_time
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.user_id
     *
     * @return the value of lesson_design.user_id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.user_id
     *
     * @param user_id the value for lesson_design.user_id
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.version_num
     *
     * @return the value of lesson_design.version_num
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public Integer getVersion_num() {
        return version_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.version_num
     *
     * @param version_num the value for lesson_design.version_num
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setVersion_num(Integer version_num) {
        this.version_num = version_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.status
     *
     * @return the value of lesson_design.status
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.status
     *
     * @param status the value for lesson_design.status
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.edu_goal
     *
     * @return the value of lesson_design.edu_goal
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getEdu_goal() {
        return edu_goal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.edu_goal
     *
     * @param edu_goal the value for lesson_design.edu_goal
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setEdu_goal(String edu_goal) {
        this.edu_goal = edu_goal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.lesson_divide
     *
     * @return the value of lesson_design.lesson_divide
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getLesson_divide() {
        return lesson_divide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.lesson_divide
     *
     * @param lesson_divide the value for lesson_design.lesson_divide
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setLesson_divide(String lesson_divide) {
        this.lesson_divide = lesson_divide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.materials_analysis
     *
     * @return the value of lesson_design.materials_analysis
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getMaterials_analysis() {
        return materials_analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.materials_analysis
     *
     * @param materials_analysis the value for lesson_design.materials_analysis
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setMaterials_analysis(String materials_analysis) {
        this.materials_analysis = materials_analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.student_analysis
     *
     * @return the value of lesson_design.student_analysis
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getStudent_analysis() {
        return student_analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.student_analysis
     *
     * @param student_analysis the value for lesson_design.student_analysis
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setStudent_analysis(String student_analysis) {
        this.student_analysis = student_analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.strategy_design
     *
     * @return the value of lesson_design.strategy_design
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getStrategy_design() {
        return strategy_design;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.strategy_design
     *
     * @param strategy_design the value for lesson_design.strategy_design
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setStrategy_design(String strategy_design) {
        this.strategy_design = strategy_design;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.focus_difficulty
     *
     * @return the value of lesson_design.focus_difficulty
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getFocus_difficulty() {
        return focus_difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.focus_difficulty
     *
     * @param focus_difficulty the value for lesson_design.focus_difficulty
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setFocus_difficulty(String focus_difficulty) {
        this.focus_difficulty = focus_difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.media_selection
     *
     * @return the value of lesson_design.media_selection
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getMedia_selection() {
        return media_selection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.media_selection
     *
     * @param media_selection the value for lesson_design.media_selection
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setMedia_selection(String media_selection) {
        this.media_selection = media_selection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.teaching_process
     *
     * @return the value of lesson_design.teaching_process
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getTeaching_process() {
        return teaching_process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.teaching_process
     *
     * @param teaching_process the value for lesson_design.teaching_process
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setTeaching_process(String teaching_process) {
        this.teaching_process = teaching_process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_design.typography_design
     *
     * @return the value of lesson_design.typography_design
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public String getTypography_design() {
        return typography_design;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_design.typography_design
     *
     * @param typography_design the value for lesson_design.typography_design
     *
     * @mbggenerated Tue Mar 28 10:11:52 CST 2017
     */
    public void setTypography_design(String typography_design) {
        this.typography_design = typography_design;
    }
}